### ISSUE TITLE
command line interface

### ISSUE THREAD

**Issue by adius** [3dcitydb/importer-exporter#1]
On the website it says:

> The 3D City Database Importer/Exporter is shipped with both a Graphical User Interface (GUI) for end-user interaction and a Command Line Interface (CLI)

Is there any documentation or examples for the CLI?

**Comment by adius** [comment]
Thanks!

**Comment by adius** [comment]
The documentation seems to be wrong as there is no `impexp.jar` file.
It should be `java -jar 3dcitydb-impexp.jar -shell` and not `java -jar impexp.jar`, right?

**Comment by clausnagel** [comment]
Yes - thanks for pointing out. We are currently rewriting the docs for the upcoming release and will take care of this.
