### ISSUE TITLE
Export as geometry doesn't work as expected

### ISSUE THREAD

**Issue by WouterDX** [3dcitydb/importer-exporter#10]
The KML/glTF export function works fine for footprint/extruded/glTF... although some glTF for my DB doesn't show up nicely in Google Earth Pro.
However, exporting as geometry only provides 2D data. The wall and roof surfaces seem to be represented without any variation in height. The altitude mode attribute is not defined in the geometry case, but setting this manually in file doesn't help.

heights for the extruded polygon of 1 building go from 0 to 13.6 using altitude mode "relative to Ground". 

Heights for the geometry polygon of the same building go from 17 to 31 ... ie. they seem to be set not 'relative to Ground'. The geometry polygon produces different entities for Wall and Roof surface. But I don't see why this should matter?
(kml files attached, rename txt to kml).

[leuvenshow2_Tile_0_0_geometry - Copy.txt](https://github.com/3dcitydb/importer-exporter/files/433031/leuvenshow2_Tile_0_0_geometry.-.Copy.txt)
[leuvenshow2_Tile_0_0_extruded - Copy.txt](https://github.com/3dcitydb/importer-exporter/files/433032/leuvenshow2_Tile_0_0_extruded.-.Copy.txt)

**Comment by WouterDX** [comment]
Note: it is definitely related to the altitude mode setting. The preferences for Altitude Mode (in KML Export>Altitude>Altitude Mode) were set to "clamp to ground". Modifying this to "relative" was sufficient to get useful data in Google Earth Pro. 

This seems like normal behavior, but it's confusing to discover because the other exports (footprint/extruded/glTF) works regardless of this setting. Perhaps this is something to be explained better in the manual?

**Comment by yaozhihang** [comment]
Thanks you very much for your comments. I've just fixed the bug that causes missing altitude mode when choosing "clamp to ground". The manual has also been revised to provide a detailed explanation of setting altitude mode. The new manual will be delivered together with the new version (3.3.0) of the 3DCityDB which will be released next week. So please stay tuned for updates on the 3DCityDB-Github.
