### ISSUE TITLE
EPSG: 4979

### ISSUE THREAD

**Issue by LJohnson7** [3dcitydb/importer-exporter#100]
Hello!
Will there be future support for EPSG: 4979? In the meantime, can someone tell me an equivalent EPSG that is supported along with the 3D-EPSG-component and the urn code used when executing the database creation shell scripts? Thank you in advance!

**Comment by FxKu** [comment]
CRS support is not related to the 3DCityDB per se, but to the underlying spatial DBMS. I assume you're using PostGIS where this CRS is not available (afaik, PostGIS is not shipped with 3D srids). On spatialreference.org you can find an import [statements](https://spatialreference.org/ref/epsg/4979/postgis/) to this EPSG code. The definition of this CRS looks like EPSG 4326. Can't this be used as well? Btw thes 3DCityDB can generate and urn code for you, if you don't specify one.

**Comment by LJohnson7** [comment]
@FxKu Thank you for the quick response! That was a great explanation and importing the desired CRS was a breeze. Also, EPSG 4326 looks like it has the same definition as well.
