### ISSUE TITLE
WallSurface textures CityGML/3dWebMapClient

### ISSUE THREAD

**Issue by ruskovski** [3dcitydb/importer-exporter#101]
Hi,

my colleague @milovanov94 and I have managed to build a 3D model based on LiDAR data (airborne laser scanning) and use 3D web map client to publish the model. You can see the current version of this model in the photo down below. We are still working on this model and hoping to improve it by much. We have managed to integrate ortophoto imagery to add the texture to the roofs (trough FME).
![Capture](https://user-images.githubusercontent.com/50613107/65581723-4189cf00-df7c-11e9-9ad7-33803969cbc4.JPG)

The question we have is following: how would you add texture to the walls? We have seen some examples where it had been done, but we are not sure how to achieve this part. Although many commercial solutions offer this, we are searching for an open-source one, if possible.
Any advice or direction would be appreciated. 

Thank you in advance,
Sincerely
Igor

**Comment by FxKu** [comment]
Do you have oblique imagery? Maybe with FME you could repeat the same process if you would rotate the 3D-model in the same angle as the photo. But in general, I have no clue how it's done :smiley:

I'm also not aware of OS tools. Have you asked in FME online forums as well?

**Comment by BWibo** [comment]
Hey there,
[this](https://knowledge.safe.com/articles/904/writing-citygml-example.html) might be a point to start. However, the untangling of images not covered. 
I also found [this](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=12&ved=2ahUKEwigqpixxPDkAhVUoVwKHY1yByAQFjALegQIARAC&url=http%3A%2F%2Fisites.info%2FPastConferences%2FISITES2014%2FISITES2014%2Fpapers%2FB12-ISITES2014ID155.pdf&usg=AOvVaw2oO5Mq7a_gC0M5VIGdMWZ6) doing a quick search. This [PhD](https://www.pf.bgu.tum.de/pub/2015/iwaszczuk_phd15_dis.pdf) could be helpful too. There is much more literature available online.

**Comment by clausnagel** [comment]
Closing because this is not an Importer/Exporter issue.
