### ISSUE TITLE
recalculate feature envelope while exporting CityGML with LoD-Filter

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/importer-exporter#104]
While running a CityGML-Export, the envelope information of each feature are currently read from the `ENVELOPE` column of the `CITYOBJECT` table and dann propagated to the Cityobject's `boundedBy` property. This may result in an inconsistency problem when the LoD-filter is activated. 

For example, a CityGML-Building dataset could have LOD0 and LOD2 representations in the database at the same time. When exporting Buildings with only LOD0 representation, the envelope of each exported CityGML feature should not be retrived from the CITYOBJECT table directly, but shall be recalculated based on the LOD0 geometries of the respective building object.

**Comment by clausnagel** [comment]
Implemented with #239
