### ISSUE TITLE
Colouring objects according to values in 3dcitydb

### ISSUE THREAD

**Issue by christianbraun** [3dcitydb/importer-exporter#105]
Hi,
I am wondering how it is possible to colorise objects in gltf according to a classification scheme. Assuming I have e.g. buildings and want to apply a schema which shows their assessment about e.g. PV generation and display it in the 3dwebclient.
Is there a way to do it with the importer-exporter?
I couldn't find any documentation.

Thanks a lot in advance,
Christian

**Comment by Son-HNguyen** [comment]
I don't think that it is generally possible to color a city object based on some of its values. But for your use case of displaying PV values perhaps @BWibo could give some input here.

**Comment by BWibo** [comment]
Hey there, 
the coloring we do in our solar application (see [here](https://www.lrg.tum.de/gis/forschungsthemen/stadt-und-energie/#c863)) is performed by the application itself. We just export the textured city model using the ImporterExporter. As far as I know this can't be done using the ImporterExporter directly. This would be a nice feature to have!

However, commercial GIS software like [FME](https://www.safe.com/) should allow for developing a workflow that is capabale to color building faces according to e.g. an attribute value containing a classification.

**Comment by clausnagel** [comment]
Closing due to missing feedback. Feel free to re-open if you have further questions.
