### ISSUE TITLE
COLLADA/glTF export produces altitude differences between Google Earth and Cesium

### ISSUE THREAD

**Issue by walterogrady** [3dcitydb/importer-exporter#11]
The COLLADA/glTF export function creates files with objects that align correctly with the Google Earth terrain altitude but not with the Cesium terrain. Is that correct and is there a method to align the objects to the Cesium terrain?

**Comment by yaozhihang** [comment]
Unfortunately, no. 
In Google Earth, we can use the "relative to ground" altitude mode to ensure that the 3D models can always be perfectly placed on the Earth surface regardless of whether the terrain is enabled or not. However, the current version of Cesium doesn't support this feature yet.

**Comment by walterogrady** [comment]
Is there a work around (hack :-) )?

**Comment by yaozhihang** [comment]
In my opinion, one possible solution could be to use the FME software to adjust the z-coordinates of the CityGML objects according to the DEM data from which the Cesium Terrain model has been derived.   
The source of the worldwide DEM data is available via:
https://cesiumjs.org/stk-world-terrain.html

The newly created/processed CityGML data should be imported into a 3DCityDB instance again. Then, by choosing the option "Use original z-coordinates without transofrmation" combined with the "absolute" altitude model with "no offset", the exported KML/glTF models should be able to be properly visualized on the Cesium terrain.

**Comment by walterogrady** [comment]
Thank you for the tip.

I now create CityGML files that use the GPS Ellipsoidal Height for the altitudes. Cesium seems to use this for altitude. I use the export options you suggested and it works so far.

For anyone who is interested here is a calculator that lets you calculate the GPS Ellipsoidal Height: 
https://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height-calculator.html
GPS Ellipsoidal Height = Orthometric Height + Geoid Height 
Orthometric Height is height above sea level and is used by Google Earth. The difference between Cesium altitude and Google Earth altitude is the Geoid Height and that varies with location.

**Comment by yaozhihang** [comment]
Excellent! thanks very much for sharing your great work with us.

**Comment by clausnagel** [comment]
Closing, since a solution was found. Should your problem persist, feel free to re-open this discussion any time.
