### ISSUE TITLE
How should I use it with ADE?

### ISSUE THREAD

**Issue by scar95** [3dcitydb/importer-exporter#110]
Hello.
I want to use City GML ADE with 3D City DB.
For example, do you need a new TopLevel to create child elements of City Furniture, such as NoiseADE's NoiseCityFurnitureSegment?
Or can I use it as a child of City Furniture?
Like this.
![image](https://user-images.githubusercontent.com/26371955/72240599-f4fbf980-3627-11ea-8b54-4d9efed9cb74.png)
or
![image](https://user-images.githubusercontent.com/26371955/72240750-5de37180-3628-11ea-8a9c-ccbd172fca66.png)
Or both?
And Do I need to build lib like Imp / Exp to use Kml Exporter with ADE?

**Comment by yaozhihang** [comment]
Hi @scar95, the both ways are supported by the CityGML ADE mechanism and the 3DCityDB ImpExp APIs.
However, the current KML/COLLADA/glTF-Exporter doesn't provide APIs for handling CityGML ADEs. These APIs will probably be added in the next major release v4.3.0. Please stay tuned for updates on the this Github-Repo.

**Comment by clausnagel** [comment]
APIs have been added with version 4.3.0. Closing this issue now.
