### ISSUE TITLE
Balloon to export multiple building addresses

### ISSUE THREAD

**Issue by matteomandrile** [3dcitydb/importer-exporter#129]
Hello!

I am working on a thesis for a master in BIM about IFC and CityGML interoperability. 
I would like to create a customized google earth balloon that allows exporting multiple addresses related to a building. Unfortunately, I am not really confident with HTML syntax, however, I was able to slightly modify the template to suit my needs (you can find it here attached). 

I edited the **charset** from **windows-1250** to **UTF-8** in the _BalloonSource_Buildings_template1_ to have more character and symbols:
`    <meta http-equiv="content-type" content="text/html; charset=utf-8">`
![image](https://user-images.githubusercontent.com/8726351/90959484-b8389080-e49b-11ea-905d-04c4531cc1bc.png)

I also added other generic attributes that I need to export and visualize:
`    <table width=392>
    <tr><td><b>Cadastre municipality code:</b> <3DCityDB>CITYOBJECT_GENERICATTRIB/STRVAL[ATTRNAME='ks_mun']</3DCityDB></td></tr>
    <tr><td><b>Cadastre Municipality Name:</b> <3DCityDB>CITYOBJECT_GENERICATTRIB/URIVAL[ATTRNAME='ks_mun_name']</3DCityDB></td></tr>
    <tr><td><b>Cadastre Building Number:</b> <3DCityDB>CITYOBJECT_GENERICATTRIB/STRVAL[ATTRNAME='ks_n']</3DCityDB></td></tr>
    <tr><td><b>SID:</b> <3DCityDB>CITYOBJECT_GENERICATTRIB/STRVAL[ATTRNAME='sid']</3DCityDB></td></tr>
    <tr><td><b>Year of renovation:</b> <3DCityDB>CITYOBJECT_GENERICATTRIB/STRVAL[ATTRNAME='year_of_renovation']</3DCityDB></td></tr>
    </td></tr>
    </table>`

However, I am not able to figure out how to export multiple addresses in a format similar to the example below (from a publication by Prof. Agugiaro).
![image](https://user-images.githubusercontent.com/8726351/90959664-a0add780-e49c-11ea-8cc8-a127356cdc6d.png)

It would be possible to have an example for such action? I believe that this is a quite recurrent situation, and having a balloon template to start with would be great for who (like me!) do not have much coding experience!

I have all the address information in the DB as per the image below, and the link to the building uses the _address_to_building table_.
![image](https://user-images.githubusercontent.com/8726351/90960329-3b101a00-e4a1-11ea-9ba9-37caa02b36f8.png)

Thank you for your time!

**Comment by matteomandrile** [comment]
Any idea?

**Comment by yaozhihang** [comment]
Hi, 
i created a simple balloon template. i hope it could help you. 
[BalloonSource_Buildings_template3.zip](https://github.com/3dcitydb/importer-exporter/files/5146920/BalloonSource_Buildings_template3.zip)

![image](https://user-images.githubusercontent.com/5942971/91661257-218f5380-eadb-11ea-9bab-2ab437cf4464.png)

**Comment by matteomandrile** [comment]
Thank you very much @yaozhihang !

I was able to integrate part of this template in my custom balloon, it was very useful to understand the mechanism!
![image](https://user-images.githubusercontent.com/8726351/91710815-27da0a00-eb85-11ea-8a3c-eb718c2ed487.png)
