### ISSUE TITLE
Do exported glTF models follow the 3D Tiles specification?

### ISSUE THREAD

**Issue by jorgeyp** [3dcitydb/importer-exporter#13]
Hello:

I'm not sure if this is the best place to ask questions, I apologise otherwise.

I want to use Cesium to visualise BIM files as 3D buildings and 3DCityDB looks like a great solution. However, I plan to use the standalone Cesium viewer once they release the 3D Tiles branch.

Do you know if it is possible to load the 3DCityDB glTF tiles as a `Cesium3DTileset` into Cesium? In the other case, do you plan to implement 3D Tiles in the future?

Thanks and congratulations on the recent realease!

**Comment by lucasvw** [comment]
Hi Jorgeyp, 

The 3DCityDB cannot export b3dm files. These b3dm files make up the Cesium3DTileset (for buildings that is, for pointclouds this would be i3dm files..).

We have however a converter which creates b3dm files from a 3DCityDB.. but its not open-source unfortunately..

**Comment by clausnagel** [comment]
Feel free to check out the following 3d web maps. They use Cesium [3D Tiles](https://github.com/AnalyticalGraphicsInc/3d-tiles), and the b3dm tiles have been directly created from 3DCityDB content using the converter mentioned by @lucasvw. 

http://www.businesslocationcenter.de/wab/maps/main/
http://www.businesslocationcenter.de/berlin3d-downloadportal/
http://wiesbaden.virtualcitymap.de/
http://bottrop.virtualcitymap.de/
http://demo.virtualcitymap.de/

**Comment by clausnagel** [comment]
Closing this issue. Feel free to re-open if you have further questions.
