### ISSUE TITLE
Energy ADE Support?

### ISSUE THREAD

**Issue by matteomandrile** [3dcitydb/importer-exporter#132]
Hello, 

I understood that the Energy ADE extension for the Importer/Exporter is still not available (true?). 
However, I was able to extend my 3dcityDB with the energy ADE, following the documentation. 

I was wondering what would be a viable option to import and export CityGML files with energy ADE information into the DB.
Maybe an FME Workbench to connect to the DB? Any suggestion would be greatly appreciated!

**Comment by clausnagel** [comment]
Great to hear that you were able to create additional tables for the EnergyADE. I assume you were using the ADE Manager Plugin?

Well, no, there is no open source EnergyADE extension for the Importer/Exporter available yet. Implementing such an extension is definitely doable, but the EnergyADE is really huge and it would require some work. Funding or contribution would therefore be very welcome. 

I guess FME would indeed be an option to load and extract data. There is also an [EnergyADE module for citygml4j](https://github.com/citygml4j/energy-ade-citygml4j). Based on this, you could start implementing an extension for the Importer/Exporter. We just recently added an extension for the real-world [i-UR ADE](https://github.com/3dcitydb/iur-ade-citydb) to the 3DCityDB project. This might be helpful and serve as template.

That said, my company [Virtual City Systems](https://vc.systems/) offers an EnergyADE extension for the 3DCityDB as commercial product. Let me know if this is an alternative as well.

**Comment by clausnagel** [comment]
Virtual City Systems has contributed their EnergyADE extension implementation as open source to the 3DCityDB project. Check it out here: https://github.com/3dcitydb/energy-ade-citydb

Hope this is useful for you. Please post issues in that repository.
