### ISSUE TITLE
Automatically calculate the BBox for KML/COLLADA/glTF exports

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/importer-exporter#138]
A KML/COLLADA/glTF export requires to either provide a list of gml:ids or a BBox. Both inputs should rather be optional and if omitted, the exporter should calculate the required BBox automatically in the background. This should even be the default option. If additional export filters are provided, the BBox should only be calculated based on the features matching the filters. 

See also the discussion in PR #96.

**Comment by yaozhihang** [comment]
Completed in this PR https://github.com/3dcitydb/importer-exporter/pull/153.
