### ISSUE TITLE
Possible precision issue on import/export

### ISSUE THREAD

**Issue by stirringhalo** [3dcitydb/importer-exporter#14]
Apologies if this would be better served in a different 3Dcitydb repo.

Hi all, I have a project, https://github.com/stirringhalo/osm2citygml, which is the process of going from OSM, to 3D, to CityGML for 3DCityDB. Latest version isn't committed just yet, but for the most part, it works quite well minus some coordinate translation + axes rotations issues.

However, I do have an issue which appears to be a precision issue related to imports/exports. On the left of the picture is 1WTC first in Cesium, exported as GLTF and the right is the original CityGML, when viewed in FME. All the way along, the OBJs and CityGML look good with no visible gaps except for when viewed as exported tiles. I haven't tried with WFS or exporting a CityGML and double checking.

![image](https://cloud.githubusercontent.com/assets/14035518/18597614/c2bfc67c-7c1c-11e6-9fa3-0843b1877a4b.png)

I'm not sure, but I suspect perhaps the issue is in import and data precision.

If you want, I can provide the GML and even a dump of the DB.

**Comment by stirringhalo** [comment]
Followup, I exported back to CityGML and viewed in FME. Issue not apparent. It might be an issue in GLTF.

**Comment by yaozhihang** [comment]
Hi, could you share a weblink allowing us to download your CityGML data which, at best, only contains the 1WTC building object?

**Comment by stirringhalo** [comment]
[test.gml.zip](https://github.com/3dcitydb/importer-exporter/files/478172/test.gml.zip)

Here's just 1WTC. It's missing one of the polygons (the top flat of the roof) but the sides display the same issue. Looks fine in FME.

I suspect it may actually be an issue with coincident faces. This is doing a straight grab of features out of OSM so there may be duplicate faces.

**Comment by stirringhalo** [comment]
Here's another extract, covering more of NY. I left out OSM relations in an attempt to fix. 
[ny.gml.zip](https://github.com/3dcitydb/importer-exporter/files/478309/ny.gml.zip)

This shows a similar issue on many of the building roofs.

I was able to isolate that showing the Geometry in the 3dwebclient works fine, just slow. It's in the "Collada/GLTF" that things go awry.

**Comment by stirringhalo** [comment]
@yaozhihang  Were you able to reproduce?

**Comment by yaozhihang** [comment]
Could you check the coordinate values in your GML file? It seems that they do not conform to the EPSG:3857 coordinate reference system.

**Comment by stirringhalo** [comment]
I'm closing this for now as it doesn't seem to show up in my later imports.
