### ISSUE TITLE
Error in data import

### ISSUE THREAD

**Issue by steffiarg** [3dcitydb/importer-exporter#143]
Hi!  We transform a shp file to gml, we use EPSG: 22174. When we want to import it into the database, it throws us the following error:

![WhatsApp Image 2020-10-01 at 15 29 00](https://user-images.githubusercontent.com/67122852/94851867-6884a780-03ff-11eb-8577-46d486642cb3.jpeg)

what does it refer to?

**Comment by clausnagel** [comment]
According to GML, a `gml:LinearRing` must be defined by four or more coordinate tuples; the first and last coordinates shall be coincident to close the ring.

For example, a triangle is described by three coordinates. For the linear ring of this triangle, the first coordinate must be appended at the end to close the ring, which results in four coordinates. This is the minimum allowed number.

Your dataset obviously contains linear rings having less coordinates. These rings violate the GML specification and cannot be "repaired" during import. Thus, they are skipped by the importer.

**Comment by steffiarg** [comment]
Ahh, ready, thank you very much!
