### ISSUE TITLE
No LOD0 export using appearances?

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/importer-exporter#144]
I guess defining appearances for LoD0 geometries (e.g. footprint buildings) does not clash with CityGML rules.

The importer/exporter however greys out the possibility to export LoD0 geometries with textures (or X3DMaterials) associated to them.

Am I missing something?

BR

GA

**Comment by yaozhihang** [comment]
Could you share your CityGML dataset including the textured LoD0 geometries?

**Comment by clausnagel** [comment]
Closing due to lack of feedback. @gioagu, feel free to reopen if this is still relevant and you can share test datasets.
