### ISSUE TITLE
COLLADA export ignores color preferences

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/importer-exporter#145]
I used the test dataset "Gasometer.zip" shipped with the Importer/Exporter and imported the "tile_0_0" without textures and the "tile_0_1" with textures. When doing a COLLADA export without textures, the exporter correctly applies the colors for roofs and walls as defined in the rendering preferences dialog:

![image](https://user-images.githubusercontent.com/5517439/97040413-2b2eb800-156e-11eb-8a63-09df72cdc9c9.png)

When chosing to export with textures, the textures are correctly applied to the buildings from "tile_0_1" (see right). However, the buildings without textures from "tile_0_0" on the left are painted in grey. They do not receive the colors defined in the preferences anymore:

![image](https://user-images.githubusercontent.com/5517439/97040760-b445ef00-156e-11eb-8e97-4a8e5edcb652.png)

Intended or bug?

**Comment by yaozhihang** [comment]
This is a default behaviour since a very earlier version (maybe v1.6.0). It would be better to use the color settings in the preferences as fallback.

**Comment by Son-HNguyen** [comment]
Can confirm that it fixed the issue for this dataset.

![image](https://user-images.githubusercontent.com/5765503/99274090-2df99180-282a-11eb-9c67-6ed80463eb04.png)
