### ISSUE TITLE
Resolve the deprecated `transformBoundingBox` method in the UtilAdapter class

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/importer-exporter#154]
This method picks the lowerLeft and upperRight corners of the input bbox as stub for building the output bbox. Obviously, the result is not the _minimum bounding box_ (MBB) of the input bbox due to the distortion caused by CRS transformation (e.g. projected CRS <-> geographic CRS). In order to obtain MBB, the method `transformExtent` in the class `org.citydb.query.filter.tiling.Tiling` shall be used. We should consider moving this `transformExtent` method into the util adapter and replace the deprecated `transformBoundingBox` method.

**Comment by clausnagel** [comment]
solved with #157.
