### ISSUE TITLE
psql: error: Fatal error:  User "postgres" Ident Authentication failed

### ISSUE THREAD

**Issue by w-y-h** [3dcitydb/importer-exporter#160]
when I run "sudo sh CREATE_DB.sh" on CENTOS7 ,show "psql: error: Fatal error:  User "postgres" Ident Authentication failed"

**Comment by Son-HNguyen** [comment]
It could be ident protocol, see [here](https://serverfault.com/questions/406606/postgres-error-message-fatal-ident-authentication-failed-for-user).
