### ISSUE TITLE
connect to 3dcitydb through ssh

### ISSUE THREAD

**Issue by chenkianwee** [3dcitydb/importer-exporter#161]
Is there a way to connect to a 3Dcitydb from the importer/exporter through a SSH tunnel like in the pgAdmin settings?

![image](https://user-images.githubusercontent.com/13062600/103103404-d56aa080-45ee-11eb-9af1-e9bfdff4e736.png)

**Comment by BWibo** [comment]
SSH tunneling to a 3DCityDB Server is in general indepent of the 3DCityDB but works fine. I just tested this.

1. Make sure `AllowTcpForwarding yes` is set to `yes` in your ssh server config file (usually located at `/etc/ssh/sshd-config`)
2. Establish your ssh tunnel using: `ssh -L [LOCAL_IP:]LOCAL_PORT:DESTINATION:DESTINATION_PORT [USER@]SSH_SERVER`, e.g.
`ssh -L 5900:127.0.0.1:5432 -N user@remote-ssh-server-running-3dcitydb`. Make sure the remote port matches the port of the database running on the remote machine.
3. Connect to the 3DCityDB instance using e.g. 3DCityDB ImporterExporter using `127.0.0.1:5900` as host and port.

**Comment by chenkianwee** [comment]
Thanks it worked!!
