### ISSUE TITLE
Importer/Exporter disappears right after launching it. 

### ISSUE THREAD

**Issue by linkas** [3dcitydb/importer-exporter#170]
I have installed the "3DCityDB-Importer-Exporter-4.2.0-Setup" and have successfully created Postgres DB by configuring the "CONNECTION_DETAILS" script and running the "CREATE_DB" script. The new DB and new schemas were created. However, when I try to open the tool either clicking the "3DCityDB-Importer-Exporter.bat" file in the bin folder or double-clicking the shortcut on the desktop it not opens. I can notice only that after I clicked on the bat file the shell window appears and immediately disappears. What can be the problem and how to solve it?
Thank you in advance.

**Comment by yaozhihang** [comment]
Hi, could you run the following command line from the bin folder, and check the error messages printed in CLI console?
`> 3DCityDB-Importer-Exporter.bat`

**Comment by yaozhihang** [comment]
You could also test the latest version [v4.2.3](https://github.com/3dcitydb/importer-exporter/releases/tag/v4.2.3)

**Comment by linkas** [comment]
Thank you very much for the tip. It worked. Problem was that my JAVA_HOME environment variable didn't match with the Java installation location. I have fixed that and it worked. Thank you again.
