### ISSUE TITLE
KMLexport: Where does the exporter query the geometry (envelop) information from the database?

### ISSUE THREAD

**Issue by lisha992610** [3dcitydb/importer-exporter#173]
Hello

Currently I am trying to identify the location of the code where the KMLexporter queries the envelop information of a building from the database. 

I was able to locate the execution of the following statement in KmlSplitter.java: 
![image](https://user-images.githubusercontent.com/28436362/108166090-9fe5bd80-712e-11eb-97fc-9dec9a398407.png)

As you can see that the exported KML file contains some coordinates: 
![image](https://user-images.githubusercontent.com/28436362/108166168-c1df4000-712e-11eb-8d31-07d4963de180.png)

I wonder how and where the exporter exactly queries this information from the database in the source code. Thank you for any help.

**Comment by yaozhihang** [comment]
All SQL queries are put here:
https://github.com/3dcitydb/importer-exporter/blob/master/impexp-kml-collada-plugin/src/main/java/org/citydb/modules/kml/database/Queries.java

**Comment by lisha992610** [comment]
Thank you very much for your response. I have seen this Queries class and the sqlbuilder library. 

I am trying to translating the SQL statement to SPARQL statement for graph database, the provided sqlbuilder is quite useful for the dynamic translation in generic way (SQLstatement object --> SPARQLstatement object). But I also noticed that the **queries class** generates only **sql query string** which requires additional parser (from string to SQLstatement) for the translation. 

I wonder if there is SQLparser library can help me for dynamic translation or any exclusive library which can translate directly from SQL to SPARQL. Thank you very much in advance.

**Comment by clausnagel** [comment]
Hi @lisha992610, the `Queries` class used by the KML/COLLADA/glTF exporter in fact just uses plain strings for the SQL statements. Our internal `sqlbuilder` library is tailored to the purpose and requirements of the Importer/Exporter. It does not provide SPARQL support. Personally, I have not worked with SPARQL a lot so far, so I am not aware of a generic library that could translate between SQL and SPARQL.

I am closing this issue now. If you have found a library or solution, it would be great if you could post your experience here.
