### ISSUE TITLE
GradleBuild tasks do not rebuild on updates 

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/importer-exporter#182]
The GradleBuild tasks used for building the plugins of the Importer/Exporter do not work as expected. They only build the plugin the first time you run `installDist`. Afterwards, the tasks are skipped because the Gradle build system thinks the output is `UP-TO-DATE`. 

Steps to reproduce:
1. Make a new clone of the Importer/Exporter repository.
2. Run `gradlew installDist` from the root of the cloned repository.
3. Go into `resources/plugins/plugin-spreadsheet-generator/src` and make an arbitrary change to one of the Java source files
4. Run `gradlew installDist` again.

Observe that `> Task :impexp-client:buildSpreadsheetGeneratorPlugin UP-TO-DATE` is printed to the console. Even though we changed the plugin, Gradle does not rebuild it.

I assume the reason is the use of `outputs.dir` in the GradleBuild task definition. Before the GradleTask is executed in step 4, Gradle checks the output directory. Since it has not changed (we only changed the source files in step 3), the output is assumed to be `UP-TO-DATE` and the GradleTask is skipped.

To fix this, `inputs` can be added to the GradleTask. Gradle will then check whether the contents of `inputs` have changed in order to decide whether the task should be executed (for example, see [here](https://medium.com/@vanniktech/making-your-gradle-tasks-incremental-7f26e4ef09c3)). Alternatively, it can be fixed by cleaning the `outputs` in a separate task.

This must be checked for all GradleTasks in the build script, not just those for building the plugins.

**Comment by yaozhihang** [comment]
@clausnagel thanks for the detailed description of the issue. Fixed with 339b089.
