### ISSUE TITLE
add new version type to -r, --feature-version=<version> in delete CLI 'inactive' 

### ISSUE THREAD

**Issue by MattSmillie** [3dcitydb/importer-exporter#185]
Using the CLI to delete objects it would be nice to be able to have a method which performs a cleanup of old/terminated features by deleting only these. This currently must be done using a SQL or XML filter.

**Comment by clausnagel** [comment]
Is it sufficient to just select all terminated objects, or do you also want to be able to select only those objects that were terminated at a given timestamp?

**Comment by MattSmillie** [comment]
I think it would be sufficient to get all terminated objects

**Comment by clausnagel** [comment]
Ok, currently we allow the following values for `--feature-version`:

* `latest`
* `at`
* `between`
* `all`

We could simply add `inactive` (or maybe better `terminated`?) to this list. Or we could additionally rename the existing values like this:

* `latest`
* `valid-at`
* `valid-between`
* `all`

This way, we can still add `terminated` now but would also be able to add something like `terminated-at` in the future. But we break the API with the second proposal.

@yaozhihang, what do you think?

**Comment by yaozhihang** [comment]
@clausnagel I prefer your second proposal. As you mentioned, this allows to add an additional option `terminated-at`. This option is especially useful for cleaning up old terminated city objects. Yes, this proposal will change the existing API, I think it is acceptable.

**Comment by MattSmillie** [comment]
You could keep `at` and `between` for backwards compatibility. Then the api wouldn't break

**Comment by clausnagel** [comment]
Ok, thanks for your feedback, @MattSmillie  and @yaozhihang. Will work on a proposal and invite you both for review.

**Comment by clausnagel** [comment]
added with #192 and will be available in next release
