### ISSUE TITLE
Failed to find config file

### ISSUE THREAD

**Issue by tomeof** [3dcitydb/importer-exporter#19]
Hello,

I'm trying to use the command line Importer/Exporter. I saved the project from the GUI as "myconf.xml".
When i save myconf.xml on the desktop i get an error message _**Failed to find config file 'filepath'**_
When i save myconf.xml in the same folder with the Importer/Exporter and use relative path i get an error message _**Failed to read project settings file 'filepath'**_
I run the command line tool from the Importer/Exporter installation path.

Greetings

**Comment by rchr** [comment]
Hi,

which version of the 3DCity Importer/Exporter are you using?
And how do you specify the paths to the config file?

I was not able to reproduce your error. For instance, I sucessfully started the importer/exporter (version 3.3) with the following commands (on windows):

`java -jar lib\3dcitydb-impexp.jar -config C:\Users\myUserName\Desktop\myproject.xml -shell -testConnection` 
and
`java -jar lib\3dcitydb-impexp.jar -config .\myproject.xml -shell -testConnection`

Hope that helps!

**Comment by tomeof** [comment]
Hi,

I'm using version 3.3-build1. This is the command i give to the shell:
`java -jar lib/3dcitydb-impexp.jar -shell -config C:/Users/userName/config.xml -kmlExport C:/Users/userName/Desktop/gltf/test.kml`

**Comment by tomeof** [comment]
Hi,

It was my mistake. I specified a wrong path for the config file. I can establish a database connection. I am trying to export to gltf. Is it possible to give an absolute path in the `-kmlExport` parameter? It seems it can export only using the same path where the importer/exporter is installed.

**Comment by tomeof** [comment]
Hi,

You can close the issue. The path should use the environment separator (windows "\"). Thanks again.
