### ISSUE TITLE
Resolution conflict between org.geotools:gt-referencing and org.apache.sis-core.sis-referencing

### ISSUE THREAD

**Issue by lisha992610** [3dcitydb/importer-exporter#191]
Hello, 

Actually I am trying to integrate some equivalent java implementation of POSTGIS-buildin functions (e.g. ST_Area and so on) into importer-exporter to corporate with the SPARQL queries. I found the geosparql library (https://github.com/galbiston/geosparql-jena) which is built on The Apache SIS™ library, e.g. 'org.apache.sis.core:sis-referencing:2.0-M0070'. 

When I try to integrate this library as dependencies into the imp-exp project, it throws me the following error: 
"Caused by: java.lang.ArrayStoreException: org.geotools.referencing.factory.epsg.DefaultFactory"

After debugging, It seems the error is caused by the incompatibility of geotool and apache sis library. I don't know if this is aware from your experience. As I am new to those GIS framework. I appreaciate for any suggestion and advices. Thank you very much.

**Comment by clausnagel** [comment]
Hi @lisha992610, sorry for being unresponsive. Sounds like a very interesting project that you are working on.

Unfortunately, I have no experience with using both GeoTools and Apache SIS library at the same time and how to resolve potential conflicts between them. But yes, it seems that both libraries register different implementations for the same service interfaces via the Java `ServiceLoader` mechanism, such as many interfaces from the package _org.opengis.referencing.*_ (see, for example, the list in `META-INF/services` inside `sis-referencing-0.8.jar` from Apache SIS and `gt-referencing-23.1.jar` from GeoTools.). 

Maybe you can suppress loading the `sis-referencing-0.8.jar` from Apache SIS using Gradle? For example:

```gradle
dependencies {
    implementation('io.github.galbiston:geosparql-jena:1.1.2') {
        exclude group: 'org.apache.sis.core', module: 'sis-referencing'
    }
}
```

But I strongly assume this is a mandatory dependency and cannot simply be exluded without breaking the SIS library...

**Comment by clausnagel** [comment]
Closing due to missing feedback. Feel free to re-open if you have more questions.
