### ISSUE TITLE
Extend FeatureExportExtension interface

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/importer-exporter#197]
It would be helpful to add two methods somehow like `exportStart()` and `exportComplete()` into the interface `FeatureExportExtension`. For example, if we write a plugin to do post-process and log the processed object into a separate CSV file, we could create a file writer within the method  `exportStart()` and close the writer in `exportComplete()`.

https://github.com/3dcitydb/importer-exporter/blob/master/impexp-core/src/main/java/org/citydb/core/plugin/extension/exporter/FeatureExportExtension.java#L35

**Comment by clausnagel** [comment]
Yes, sounds like a good idea. I guess the interface would also need to handle cases where the export is aborted by the user or even terminates abnormally. Because if you open resources when the export starts, you should close them even if the export process fails.

**Comment by yaozhihang** [comment]
True, nice remark.

**Comment by clausnagel** [comment]
fixed with #200
