### ISSUE TITLE
How to export tile, So it will not make the browser freeze

### ISSUE THREAD

**Issue by wong-kene** [3dcitydb/importer-exporter#203]
I try to view tile from berlin visualization on this demo. 
https://www.3dcitydb.org/3dcitydb/visualizationberlin/

i get tile from 
https://www.3dcitydb.org/3dcitydb/fileadmin/mydata/Berlin_Demo/Berlin_Buildings_rgbTexture_ScaleFactor_0.3/Berlin_Buildings_rgbTexture_collada_MasterJSON.json
and load from my own web-map. the result is same with demo on 3DcityDB site

then i try to export other citygml (los angeles) on my own 3DcityDB.
the result is different. berlin can load data partial, but los angeles load full data on first time. So, los angeles make my browser 'not responding'

Why did it happen? any specific trick or technique for export like berlin? 
or depend on server performance?

thanks..

**Comment by clausnagel** [comment]
Please check our online user manual. The latest version is available at https://3dcitydb-docs.readthedocs.io/en/release-v4.3.0/.

- [Chapter 6](https://3dcitydb-docs.readthedocs.io/en/release-v4.3.0/webmap/index.html#) is about the 3D web map client and how to use it to visualize even large 3D city models
- [Chapter 4.6](https://3dcitydb-docs.readthedocs.io/en/release-v4.3.0/impexp/export-vis.html) is about the export of visualization data from the 3DCityDB using the Importer/Exporter, which can then be loaded with the 3D web map client. [Chapter 4.6.2](https://3dcitydb-docs.readthedocs.io/en/release-v4.3.0/impexp/export-vis-filters/tiling.html) provides details on how to tile the visualization data.

**Comment by wong-kene** [comment]
Oke thanks for your response. Now my app is running well
