### ISSUE TITLE
Import 2 File with UTM Projection, but located on different country.

### ISSUE THREAD

**Issue by ozaapt** [3dcitydb/importer-exporter#205]
i have 2 citygml file with UTM projection. there are located on different country, So has different projection number. 32748 and 31467. but both is UTM projection.
how to import it on same schema?

**Comment by clausnagel** [comment]
For both Oracle and PostgreSQL/PostGIS, all geometries stored in the same column of a table must share the same spatial reference system. So, no, it's not possible to store geometries with different reference systems in the same 3DCityDB instance. There are mainly two options:

1. Set up multiple instances of the 3DCityDB, one for each reference system. When using PostgreSQL, note that you can use one database with multiple schemas for this purpose (see [here](https://3dcitydb-docs.readthedocs.io/en/release-v4.3.0/3dcitydb/multi-schema.html)).
2. Reproject your data into one common reference system and set up a 3DCityDB for this reference system. Afterwards, you can import all your data into this 3DCityDB. We do not recommend using geographic coordinates, but maybe you could use World Mercator ([EPSG 3395](https://spatialreference.org/ref/epsg/3395/) or EPSG 3857 ).

**Comment by ozaquisba22** [comment]
thank you

**Comment by ozaapt** [comment]
thank you
