### ISSUE TITLE
Export one building only

### ISSUE THREAD

**Issue by wong-kene** [3dcitydb/importer-exporter#206]
Hello,
I have three citygml file (file A, B and C). For Each citygml contain one building. 
I import to 3DcityDB three times.

Can I export only one building, for example B only or C only?

Thanks

**Comment by clausnagel** [comment]
Yes, for sure. The CityGML/CityJSON export operation has powerful export filters. Please go through the section "Export filters" in chapter 4.5 of the user manual: https://3dcitydb-docs.readthedocs.io/en/release-v4.3.0/impexp/export.html.

Or do you mean KML/COLLADA/glTF export? Then please read the section "Export filters" in chapter 4.6: https://3dcitydb-docs.readthedocs.io/en/release-v4.3.0/impexp/export-vis.html

**Comment by wong-kene** [comment]
I was readed the docs. Bu i don't know the table and column that can filter depend on file A,B or C. I want to filter objects that uploaded on first import, second import or third import

I can't filter by atribute because all file may has same atribute

**Comment by clausnagel** [comment]
The easiest way is to set metadata when importing the data using the "Preferences -> Import -> Continuation" tab (see documentation [here](https://3dcitydb-docs.readthedocs.io/en/release-v4.3.0/impexp/import-preferences/continuation.html?highlight=creationdate)). This would allow you to use this metadata as filter when exporting the data. I suggest setting different values for the `lineage` attribute for each import. Alternatively, you could query based on the creation date of the objects (which stores the time of the database import, column `creation_date` of table `cityobject`)

**Comment by wong-kene** [comment]
Thanks @clausnagel my problem solved with 'lineage'

I use this command to import and export

IMPORT
impexp import  --lineage=xxx -H localhost -d citydb_v5 -u postgres -p admin "D:\path_tomy_file\myfile.gml"

EXPORT
impexp export-vis -H localhost -d citydb_v5 -u postgres -p admin -o "D:\path_tomy_file\myfile.gml" -D collada -l 3 -s "select id from cityobject where lineage='xxx'" -g auto -m -G -t Building

**Comment by clausnagel** [comment]
Nice solution. Wasn't aware that you are using the CLI only.

I am thinking about adding some simple CLI options for specifying attribute filters so that you do not have to use SQL statements.

**Comment by muratkendir** [comment]
I think if CLI tools used as exporter, it should be also possible to use a simple batch command like:

For X in An_Array
Do
imexp_export_statement_which_include_X
Done;

**Comment by wong-kene** [comment]
> Nice solution. Wasn't aware that you are using the CLI only.
> 
> I am thinking about adding some simple CLI options for specifying attribute filters so that you do not have to use SQL statements.

Yes, i use CLI. because all of process run automatically and dinamically via web application
