### ISSUE TITLE
Where do i have to find another the SRID and SRS?

### ISSUE THREAD

**Issue by sabahMotamedi** [3dcitydb/importer-exporter#21]
Hello,
I want to set the CREATE_DB but i want enter myself the SRID and SRS, Can i enter the Berlin SRID and SRS and the Tehran (WGS84 UTM Zone 39N) SRID and SRS together?

I don't know where must find it? This is: “urn:ogc:def:crs,crs:EPSG:6.12:25833,crs:EPSG:6.12:5783", Where do i can to find that?

Best Regards,
Sabah

**Comment by FxKu** [comment]
Hi Sabah,
you have to enter a SRID code and GML SRS NAME yourself :)
The Berlin CRS is just an example what kind of input is expected. So in your case the first parameter would be 32639, I guess (http://spatialreference.org/ref/epsg/wgs-84-utm-zone-39n/)

The second parameter is a string that should link to metadata of the CRS. We chose a layout proposed by the OGC (https://portal.opengeospatial.org/files/?artifact_id=24045). So, if you do a CityGML export this string is written to the file, too. If you load the file into another software that can interpret the string, it can pick (or at least suggest) the right CRS straight up, without having you to search for the SRID. This applies e.g. to the FZK Viewer (http://iai-typo3.iai.fzk.de/www-extern/index.php?id=2315&L=1). So the simplest version in your case would be: urn:ogc:def:crs:EPSG::32639

You cannot use two CRS in a 3DCityDB instance. But you can at least choose to export your data in another reference system (if this CRS covers the area of the DB SRID, e.g. WGS84 UTM 39N --> WGS84).

Hope that helps
Felix

**Comment by FxKu** [comment]
Hm, sounds like the error is in your CityGML file, but hard to tell from a distance.

Yes, for your model urn:ogc:def:crs:EPSG::32639 is fine. This parameter in not important for the functionality of the 3DCityDB. You can type whatever you want. It's just useful for the explained workflow. The default values (only default in the Oracle version btw) are only suitable for data in this CRS, e.g. if you want to play with Berlin datasets.

**Comment by sabahMotamedi** [comment]
Thanks a lot,
It seams is in my model, But when i want to import the Berlin dataset that error display again.
Afterwards set the 3dcitydb If i will want to import a mode from another area(like UTM zone 38) i have uninstall the all works and i start from Beginning? Or i can to set the CREATE_DB by another SRID?

**Comment by FxKu** [comment]
Well, then maybe it's a bug with the FZK Viewer...

To change the reference system after setup there is the function change_schema_srid. Please, have a look at the documentation how to use this function: p100 for Oracle and p103 for PostGIS.

If you want to work with data of both CRS, you need to create a second 3DCityDB instance with the CREATE_DB script.

**Comment by sabahMotamedi** [comment]
Thank you,
How to create second 3DCityDB? I have to copy  the CREATE_DB another foder and change it then run it by second SRID?

**Comment by FxKu** [comment]
What DBMS are you using? Postgres or Oracle? Just create another empty Database (Postgres) or User-Schema (Oracle) and run CREATE_DB on it.

**Comment by sabahMotamedi** [comment]
Thank you,
I'm using from Postgres.

**Comment by clausnagel** [comment]
Closing this issue. Feel free to re-open if you have further questions.

**Comment by goluzam** [comment]
Hi, I have a problem.
When I export data in .kml format and put it in Google Earth it goes somwehere in Africa, but I put SRID and SRS for Austria (Europe).
My code looks like: 
SRID: 25833
URN: urn:ogc:def:crs,crs:EPSG::25833,crs:EPSG::5778

Can you tell me if it is ok, or there is some mistake?
