### ISSUE TITLE
Prevent Insert Data if any error during import

### ISSUE THREAD

**Issue by wong-kene** [3dcitydb/importer-exporter#213]
I have a problem when import citygml file, i try to click 'just validate' first.
then if validation sucess, i try to import. And I got the error like my screenshoot below 

![WhatsApp Image 2021-08-30 at 08 49 01](https://user-images.githubusercontent.com/78309477/131294728-98364276-dbe7-420e-b101-c802e6468e23.jpeg)

My question **not** "How to solve this error" 
**but** 
How to prevent insert into database if any error during import process?
because this problem make me confused, data inserted but cannot be exported, so i must clear data manually on database.

Is possible to use commit or rollback? or any 3DcityDB built-in feature ?

Thanks...

**Comment by clausnagel** [comment]
The `Just validate` button performs an XML schema validation. Your errors, however, do not violate the XML schema but the GML definition of a linear ring. Thus, they are not detected by a pure schema validation. You should consider using a geometry validation tool before importing them.

> ... make me confused, data inserted but cannot be exported, ...

Why can't you export? Export should still be possible.

We use batch imports on individual tables, so it's not immediately possible to rollback a feature that involves multiple entries in different tables while commiting others. We could log the IDs of features with `ERROR` or `WARN` messages into a file that you could feed to the delete operation afterwards.

Can't you fix the tool that generates the data? I think the tool should not generate invalid rings in the first place.

**Comment by wong-kene** [comment]
@clausnagel thaks for your response,

Can you suggest Geometry Validation tools to use?

> We could log the IDs of features with ERROR or WARN messages into a file that you could feed to the delete operation afterwards.

how i know the "IDs" ?

about rollback features, I have an idea, Is this step posible?
1. set autocommit off
2. process import
3. commit complete

**Comment by clausnagel** [comment]
Yes, a "commit all or nothing" strategy is possible. I will check what it means in terms of development efforts and whether we can put it on the roadmap for an upcoming release.

Geometry validation tools:
- [val3dity](https://github.com/tudelft3d/val3dity) - open source and also available as [online service](http://geovalidation.bk.tudelft.nl/val3dity/)
- [City Doctor](https://www.citydoctor.eu/) - free software; currently undergoing a major redevelopment  
- [FME](https://www.safe.com/) - commercial "Swiss army knife" for geodata processing that can also validate geometry

The first two tools are tailored to geometry validation. FME would also allow you to build your own workspaces that not only validate geometry but also check other aspects of your data.

**Comment by wong-kene** [comment]
ok thanks @clausnagel i will validate with geometry tools first then use 'just validate' button
