### ISSUE TITLE
3D visualization for room

### ISSUE THREAD

**Issue by dikyridhlo** [3dcitydb/importer-exporter#214]
I want to create 3D visualization for room, not the building.
So, I can click on a room and show its attribute.

Is it possible?
Is it same case with 'train station demo'? (screenshot attached)

![image](https://user-images.githubusercontent.com/35356597/131446567-13e41ee9-043c-4cc5-9cc5-1f3eab9cba51.png)

**Comment by clausnagel** [comment]
Closing. Issue is discussed here: https://github.com/3dcitydb/3dcitydb-web-map/issues/69#issuecomment-911283523
