### ISSUE TITLE
Docker multi-architecture support

### ISSUE THREAD

**Issue by BWibo** [3dcitydb/importer-exporter#217]
Docker supports building images for multiple CPU architectures using [`docker buildx`](https://docs.docker.com/desktop/multi-arch/).
This is becoming more relevant, as for instance the new generation of MACs comes with `arm64` CPUs.

* [Announcement ARM MACs](https://www.heise.de/news/Apple-praesentiert-ARM-Mac-mit-Achtkernprozessor-4953652.html)
* [How to do this with Github actions](https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/)

I did some local tests, the images are available here:
https://hub.docker.com/repository/docker/tumgis/impexp-test/tags?page=1&ordering=last_updated

**Comment by clausnagel** [comment]
There have been no requests for ARM images so far, so closing this issue. We have added multi-architecture support to `citydb-tool` for the upcoming 3DCityDB v5 though.
