### ISSUE TITLE
Timeout on vis-Export , big file and many room 

### ISSUE THREAD

**Issue by dikyridhlo** [3dcitydb/importer-exporter#218]
I have a file that has 600 rooms. refer to [https://github.com/3dcitydb/3dcitydb-web-map/issues/69](url). when I upload this file, got an error like the attached image. but when I upload a small GML (which has 12 rooms) it's working well. is this application have a timeout setting? 
![image](https://user-images.githubusercontent.com/35356597/137414799-58940353-69b2-421a-99d7-3d1d2e8e8f10.png)

**Comment by Son-HNguyen** [comment]
You could try to increase the heap size (i.e. relocate more memory) and rerun the export. This has been addressed in https://github.com/3dcitydb/importer-exporter/issues/55. For the latest version of the Importer/Exporter, open the file `impexp` in the directory `bin` in your installation:
```bash
vim bin/impexp
```
and change the following line:
```bash
DEFAULT_JVM_OPTS='"-Xms1G"'
```
to something like:
```bash
DEFAULT_JVM_OPTS='"-Xms2G -Xmx4G"'
```
where:
+ `-Xms` means the initial allocated memory pool (in this case 2 GB)
+ `-Xmx` means the maximal allocated memory pool (in this case 4 GB)

**Comment by clausnagel** [comment]
Closing due to missing feedback. Feel free to re-open if you have more questions.
