### ISSUE TITLE
Add support for XPath's function calls in XML query

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/importer-exporter#219]
Currently, the XPath's function call e.g. `count` is not supported in XML query expression and the query like "_Find all buildings having at least four wall surfaces_" cannot be expressed. We could use the generic SQL query as a fallback, but it would be nice to have the support of XPath's function calls.

**Comment by clausnagel** [comment]
Will not be resolved for version 5.x of the Importer/Exporter. A SQL query can be used as fallback.
