### ISSUE TITLE
Select a part from building in web map (Cesuim)

### ISSUE THREAD

**Issue by sabahMotamedi** [3dcitydb/importer-exporter#22]
Hello,
I'm working on 3D Cadastre, I want to select different parts (lots) from a building and display attribute it.

Can you  help me for this?

I don't want to select whole of a building, Do you have code for selecting different parts from building? 

Thank you,
Sabah

**Comment by yaozhihang** [comment]
No, we don't have open source code for this functionality. It is only supported by the commercial 3D web application developed by the company [virtualcitySYSTEMS](http://www.virtualcitysystems.de/en/)

**Comment by clausnagel** [comment]
Closing this issue. Feel free to re-open if you have further questions.
