### ISSUE TITLE
FATAL: password authentication failed for user "user1"

### ISSUE THREAD

**Issue by Saji70** [3dcitydb/importer-exporter#222]
Dear 3DCitydb team

I encounter with:

"[23:45:40 ERROR] Connection to database could not be established.
[23:45:40 ERROR] Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "user1""

Any advice for resolving it?

My pg_hba.conf file is as follow:

[pg_hba.zip](https://github.com/3dcitydb/importer-exporter/files/7449271/pg_hba.zip)

**Comment by BWibo** [comment]
According to the error msg the *username* and *password* combination you used is not correct.
You `pg_hba.conf` file is configured to required a password for login to you database from all IP4 and IP6 addresses:
```
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
```
If you desire a different configuration, see the official docs on [pg_hba.conf](https://www.postgresql.org/docs/14/auth-pg-hba-conf.html).

Otherwise, check your connection credentials (username, password) and try again.

For further assistance we will require more information:
* How are you runing 3DCityDB (Native setup, Docker)?
* What client are you using to connect (GUI/CLI/CLI using Docker images)?
* Eamples of the commands you are trying to run

**Comment by Saji70** [comment]
Thanks Bruno for the response

I am running 3DCityDB on the same machine (Ubuntu 18.04).

I installed 3DCityDB using its GUI installer and run it using _3DCityDB-Importer-Exporter_ script which open GUI with multiple tabs including Database. 

I'd like to import GML file from import tab but the error for password occurred. 

I just install Postgres on my OS and run 3DCityDB-Importer-Exporter script. I did not set any username or password anywhere which It ask me about it !!!

I think some pre-settings for defining new database instance should be done but I don't know how should be done?

![DB_error](https://user-images.githubusercontent.com/85385094/139732243-15f7ff62-133a-40c6-97d8-8b2ecfcf9f17.png)

**Comment by clausnagel** [comment]
I guess you have missed some mandatory steps for setting up the 3DCityDB. It's not sufficient to just install PostgreSQL...

1. Install PostgreSQL with the PostGIS extension.
2. Create a user that shall be the owner of the 3DCityDB (you could also use the predefined `postgres` user but it's highly recommended to create a new non-root user).
3. Create a database and assign the user from step 2 as owner.
4. Use the `CREATE_DB` script to set up the 3DCityDB schema in your database from step 3.

I recommend using a database tool like [pgAdmin](https://www.pgadmin.org/) for steps 1 - 3. Only after having successfully completed steps 1 - 4, you can try and connect to your 3DCityDB database using the Importer/Exporter.

When creating a user in step 2, also assign a password for this user. If you want to connect to your database without providing a password, change the auth-method in your pg_hba.conf file from `md5` to `trust` (not recommended).

For more information on how to set up the 3DCityDB, see chapter 1.3 of the user manual: https://3dcitydb-docs.readthedocs.io/en/version-2021.1/first-steps/index.html#

If you are not too experienced with setting up databases and users under PostgreSQL, using the [3DCityDB Docker image](https://3dcitydb-docs.readthedocs.io/en/version-2021.1/first-steps/docker.html) might be a better alternative.

**Comment by clausnagel** [comment]
Closing due to missing feedback. Feel free to re-open if you have more questions.
