### ISSUE TITLE
Enhance the `Validate XML query` process

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/importer-exporter#224]
The `Validate XML query` process only checks whether the XML query entered into the input field *conforms to the XML schema*. Should we also compile the query to identify more possible errors when clicking this button (like incorrect names and namespaces of features and attributes, incorrect XPath expressions, data type issues, etc.)? Not sure if this is easy to implement though.

**Comment by clausnagel** [comment]
Implemented with #238
