### ISSUE TITLE
Allow to choose multiple CSV files for the Import list filter

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/importer-exporter#225]

**Comment by clausnagel** [comment]
I checked this feature wish and it requires quite some changes to the `IdList` core API on which the import list filter is built. Thus, these changes will also have an impact on all plugins using an `IdList`.

Some additional questions:
- Currently, the CSV file to be parsed is shown using a simple `JTextField` in the UI. I guess this should be changed to a `JList` to show multiple files? We could keep a simple `JTextField` but then would need a unqiue separator (for example embrace all files names by double quotes and use a white space inbetween: "fileA" "fileB" "fileC").
- All files must, of course, share the same CSV settings. When doing a preview, I would still just preview the first file, not all files. Agreed?

**Comment by yaozhihang** [comment]
Thanks for looking into this feature wish.
- `JList` looks better. 
- Fully agree

**Comment by clausnagel** [comment]
Solved with #271
