### ISSUE TITLE
Support For Raster Reliefs

### ISSUE THREAD

**Issue by daniel-de** [3dcitydb/importer-exporter#23]
Hi,
we recently came across more and more files with raster relief features, which seam to be not supported at the moment. Are there plans to add support for these files in the near future?

kr
Daniel

**Comment by FxKu** [comment]
Hi Daniel,

there is no support for the RasterRelief Feature in the Importer Exporter. You are right. It's supported by [citygml4j](https://github.com/citygml4j/citygml4j/blob/master/resources/jaxb/schemas/CityGML/2.0.0/relief.xsd) though.

I think, this has two reasons. 
First: Up till now, there has been no user demand for storing raster reliefs in the 3DCityDB. Personally, I haven't seen a CityGML file yet that contains raster data or to be more precise: a gml:RectifiedGridCoverage feature. How do your files look like?

Second: To transfer geodata from Java to the database we are using the JDBC drivers of Oracle and PostGIS. I think there's no native support for the raster data types. To import raster files both DBMS recommend certain tools. Maybe there is a solution using [GeoTools](http://docs.geotools.org/stable/userguide/library/coverage/jdbc/index.html#im-jdbc) or [this](http://gis.stackexchange.com/questions/184094/how-to-insert-raster-in-postgis-from-java-jdbc) approach.

So a trick might be: Import the raster files into your DB using these tools and do some rearrangements that it fits to the table structure of the 3DCityDB (Relief_Feature -> Relief_Feat_To_Rel_Comp, Relief_Component, Raster_Relief, Grid_Coverage).

So, to answer your question. No, there are no plans to support raster reliefs in the Importer/Exporter in the near future.

lg Felix

**Comment by daniel-de** [comment]
Hi Felix,

thanks for the fast response.
We have files with gml:RectifiedGridCoverage feature, but I'm afraid that it is not possible to share example data at the moment (have to check the NDAs first...).
The raster is textured using GeoreferencedTextures with non resolvable links to a target=#ground. It would help us a lot, if we could use the import-export tool to access these textures. They are imported to the surface_data and tex_image tables, but are not exported as GeoreferencedTextures, because of the unresolvable XLINK?!?

kr,
Daniel

**Comment by clausnagel** [comment]
Since the geometry of the terrain is not imported due to lacking support for RasterRelief in the importer, the XLinks from the GeoreferencedTexture to the terrain geometry cannot  be resolved on the database level. This explains log messages about unresolvable XLinks.

Are your GeoreferencedTexture elements modeled as global appearances (i.e., linked to` <CityModel>` through an` <appearanceMember>` property)? The exporter suppresses global appearances if the referenced geometry has not been exported.

**Comment by daniel-de** [comment]
The GeoreferencedTexture elements are modeled as global appearances. That means we have to find a "little" workaround using citygml4j.

I could share a little testing dataset, if you are interested in an example for gml:RectifiedGridCoverage...

**Comment by clausnagel** [comment]
Yes, I am interested. Did you succeed to create a workaround using citygml4j?

**Comment by clausnagel** [comment]
Closing due to missing feedback.
