### ISSUE TITLE
Incorrect height in kml

### ISSUE THREAD

**Issue by kam1107** [3dcitydb/importer-exporter#232]
Hi,
I am trying to convert NYC citygml model to kml format and load into google earth. However, the height of buildings are not correct.
![image](https://user-images.githubusercontent.com/13587147/142623178-59bb5c01-ae0f-463f-8059-e85d576af20b.png)
I use EPSG=2263 but not sure how to set gml:srsName. Could you please offer some help?

Many thanks!

**Comment by Son-HNguyen** [comment]
Is the EPSG code you entered the same as the SRID given in the CityGML file (in the `envelope` element for example)? You can also find the GMLSRSNAME there. Additionally, you can adjust the elevation in the Importer/Exporter, see [here](https://3dcitydb-docs.readthedocs.io/en/latest/impexp/export-vis-preferences/elevation.html).

**Comment by kam1107** [comment]
I used the NYC CityGML model in this link: https://www1.nyc.gov/site/doitt/initiatives/3d-building.page
and it provides:
![image](https://user-images.githubusercontent.com/13587147/142797197-01adcef5-1235-428b-87b3-5e57d4aca615.png)
where the Berlin sample contains:
![image](https://user-images.githubusercontent.com/13587147/142797464-07a04e5f-6389-4bef-94f6-15120545baf5.png)

I tried to enter 'urn:ogc:def:crs,crs:EPSG::2263' for srsname and the results looks like the image above. How should I find the correct srsname 🤔？

**Comment by clausnagel** [comment]
Hi @kam1107, use `2263` as SRID when setting up the 3DCityDB instance. The `srsName` attribute could simply be "EPSG:2263" as in the original datasets. You can easily fix the KML export by deactiving the "Use orginal height values without transformation" in the elevation settings:

![image](https://user-images.githubusercontent.com/5517439/142861069-cba9508e-3f19-4c8e-b5c1-f0987c30f02f.png)

When you choose COLLADA as output format, there are still issues with the size of the buildings. The reason is that the original data uses US survey foot while the COLLADA export expects meters. @Son-HNguyen, this might be a bug that needs to be fixed.

**Comment by kam1107** [comment]
Hi @clausnagel, thanks for your tips! I did as you suggested:
![image](https://user-images.githubusercontent.com/13587147/143237924-aa2e5745-1fc7-4cf5-9bf6-d208a1fc6df2.png)
![image](https://user-images.githubusercontent.com/13587147/143237982-54b7868d-acba-4cf2-8a58-9a2f9a654dc8.png)
but the displayed height is still incorrect (I exported geometry). Does foot and meter conversion affect geometry as well?

**Comment by clausnagel** [comment]
Hm, strange, I tested again with the latest version 5.0.0 of the Importer/Exporter and when using the above setting the result looks fine for me. I just tested with a part of Manhattan. 

![image](https://user-images.githubusercontent.com/5517439/143241610-b80d4e83-5c7b-440d-942c-4085bb8d1384.png)

**Comment by kam1107** [comment]
Emmmm no I still cant get it right. Here's what I do:
(1)
![image](https://user-images.githubusercontent.com/13587147/143381320-cbaded77-d0c0-428c-a8c9-7d37921350e9.png)
and then run CREATE_DB.sh
(2)
In 3D city importer/exporter, I untick the 'w/o transformation' setting and import the model:
![image](https://user-images.githubusercontent.com/13587147/143382011-ed0b0829-e083-49f1-849a-9f908ca14f6f.png)
(3)
Go to VIS Export and select a subregion:
![image](https://user-images.githubusercontent.com/13587147/143382086-d6496e32-2810-4b41-9055-a958943206c1.png)
(4) 
and I load the kml model into GE pro:
![image](https://user-images.githubusercontent.com/13587147/143382149-6df0648d-46b9-4f3c-9c91-4b39885d5e0f.png)

Did I miss anything 🤔?

**Comment by clausnagel** [comment]
The steps seem to be ok. You only need to uncheck the `w/o transformation` for the VIS Export, it does not have an impact on the import in step 2. But that's only a minor comment.

Can you please share your CityGML dataset just to be sure that we are using the same input data? And maybe also your exported KML? 

If it's not the Importer/Exporter, maybe the database makes the difference? What PostGIS version are you using?

@Son-HNguyen, have you also tried to export the model? Do you face the same issues or does it work for you?

**Comment by Son-HNguyen** [comment]
Using the bounding box and settings provided by @kam1107, this is what I could reproduce:
![image](https://user-images.githubusercontent.com/5765503/143491370-a823b619-dd0a-4296-a168-1363c4db240d.png)
I also used the Importer/Exporter 5.0.0.

We might indeed need to have a look at your dataset and the database info as @clausnagel said.

**Comment by kam1107** [comment]
Here's the link to the gml&kml file: https://drive.google.com/file/d/144pURsnqKfKjgenHrNKfOvForpCOGt5i/view?usp=sharing
and my PostGIS version is 3.1.4
also I use Importer/Exporter 5.0.0

**Comment by clausnagel** [comment]
Thanks for sharing the data and the database info.

I ran my tests on PostGIS 2.3.3. With PostGIS 3.1.2, I can actually reproduce your issue.

**Comment by kam1107** [comment]
Okay..... I also noticed there is an `affine transformation' configuration in Preferences/Import/Geometry. Does that affect the imported geometry? Actually, I tried to modify this matrix but the exported kml remains the same.

**Comment by clausnagel** [comment]
Yes, affine transformation works. Tested with the following matrix:

![image](https://user-images.githubusercontent.com/5517439/143553307-976ce2cf-3ddd-4532-a88a-fa692b34ef49.png)

Alternatively, you can also use `ST_Scale` to directly adapt the geometries stored in `SURFACE_GEOMETYR` and `CITYOBJECT`:

```sql
update surface_geometry
set geometry=st_scale(geometry, 1.0, 1.0, 0.3048)
where geometry is not null;
```

```sql
update cityobject
set envelope=st_scale(envelope, 1.0, 1.0, 0.3048)
where envelope is not null;
```

**Comment by kam1107** [comment]
Yes! that works for me as well! Many thanks!
