### ISSUE TITLE
Question about import citygml data into citymodel table

### ISSUE THREAD

**Issue by chantelYiu** [3dcitydb/importer-exporter#251]
Hello,

I have tried to import a CityGML file using by the Importer-Exporter as attached. [citygml.txt](https://github.com/3dcitydb/importer-exporter/files/8581092/citygml.txt)(I copied the content to .txt in order to upload)
For the city object data, they are imported success into "cityobject" table. However, I found that there are no records for the data (e.g.gmlid) of "citymodel" table and linked record of "cityobject_member" table after import. Are there any config or setting is missing when i'm importing? 

3dCityDB version: 4.1.0
Importer/Exporter version: 4.3.0

I am new on 3dcitydb and many thanks for your help. 
![image](https://user-images.githubusercontent.com/104556686/165713029-d478900c-7f0d-47ee-8859-f836d06098a4.png)
![image](https://user-images.githubusercontent.com/104556686/165713508-1692eeeb-9d7b-4b46-a9af-bd81dc19de94.png)
![image](https://user-images.githubusercontent.com/104556686/165713821-fe50ef8d-0322-45ee-b6d1-2f5d50322740.png)

**Comment by clausnagel** [comment]
The `CITYMODEL` table is not populated by the Importer/Exporter.

**Comment by chantelYiu** [comment]
thanks @clausnagel 
that means I need to import citymodel data into table manually? Or any other methods/hints to let CITYMODEL related to CITYOBJECT table? 
It's becasue i want to handle city object data group by city model id. Thanks!!

**Comment by clausnagel** [comment]
Yes, if you want to use the `CITYMODEL` table, you have to populate and manage this table and the `CITYOBJECT_MEMBER` table yourself.

Alternatives:
1. Assign an attribute to your city objects in your input files (e.g. a generic attribute or an external reference). Then you could identify/group your city objects by the value of this attribute.
2. Enter a value for the "Data lineage" input field on the "Preferences -> Import -> Continuation" tab. The value you enter here is stored in the `LINEAGE` column of `CITYOBJECT`. Note that the value is stored for all city objects in one _import session_, so make sure to only import one `<CityModel>` at a time and change the lineage value between imports. In contrast to option 1, the lineage is not exported by default, so it does not appear in your CityGML data.
3. Use a `CityObjectGroup` to group your objects.

**Comment by chantelYiu** [comment]
"Data lineage" is a great solution. I will try on it.
Thanks for your patience and help!!! @clausnagel

**Comment by chantelYiu** [comment]
Sorry for bothering again as i have a new question related to this issue. 
Due to all the gml parent id of city object in my CityGML file are only linked to city model gml id, it makes the relationship is missing between top-level feature and its child. For example, the building_id are missing inside "building_installation" table as below screenshot. 
![image](https://user-images.githubusercontent.com/104556686/167582059-7dd2f562-f66f-4612-969d-abe26bbc0d61.png)

It makes me cannot export the data inside building_installaion when i exported to same citygml file. 
The reason i know that only top-level feature object can export. 
But are there any ways i can export the all cityobject even i have the "data lineage"?

Thanks for your patience!!

**Comment by yaozhihang** [comment]
You are right, only top-level city objects can be exported. If you want to export building installations, they must be the children of building objects.

**Comment by chantelYiu** [comment]
Okay. Many thanks!!
