### ISSUE TITLE
Question about export KML file

### ISSUE THREAD

**Issue by chantelYiu** [3dcitydb/importer-exporter#252]
Hello, 

When i tried to export to VIS and show the buildings on Web Client by the sample data. I got this result. 
![image](https://user-images.githubusercontent.com/104556686/166652897-9968a7a0-39a4-4a61-94b0-6c2f4d773ebf.png)

GML file: 
[Railway_Scene_LoD3.zip](https://github.com/3dcitydb/importer-exporter/files/8619028/Railway_Scene_LoD3.zip)

The files of VIS Export:
[test.zip](https://github.com/3dcitydb/importer-exporter/files/8619036/test.zip)
![image](https://user-images.githubusercontent.com/104556686/166653686-fd21aeb8-8a0e-425f-83ad-a4b192af8524.png)

3dCityDB version: 4.1.0
Importer/Exporter version: 4.3.0
SRS: 
![image](https://user-images.githubusercontent.com/104556686/166653837-d432ae39-6445-4aa2-a01a-be51efed66b5.png)

I checked the data is imported success but fail to show on Web Client. Any settings/config is wrong? 

Thanks so much!

**Comment by t16h05008** [comment]
Hi, I just imported the files you provided into the web-client. If you open the console and zoom to the area, you can see that the web-client looks for .gltf files. Your directory contains .dae files, so the client can't find anything.

![image](https://user-images.githubusercontent.com/49350695/167047470-9f610d10-05d5-40fb-b7ba-33df77a238df.png)

I have not tested this, but you can try to go to the 'Preferences' tab in the imported/exporter and look at the 'VIS Export' entry. There should be an option to export glTF-files (with some further options).

**Comment by chantelYiu** [comment]
After I checked "export giTF-files" and "Force surfaces to be double sided", it works but i dont know what is the double sided means. Anyway thanks! @t16h05008

**Comment by chantelYiu** [comment]
Hi, i would like to reopen as i found an issue related to VIS export. 
I have imported a citymodel and there is an image which is named `Material #15.jpg` as below.
![image](https://user-images.githubusercontent.com/104556686/168206260-05c96cdd-f04e-4ec8-8cec-bab463d153de.png)

When I export the glTF-files and view the model on Web Client, the model cannot show and an error is shown "Fail to load image". 
![image](https://user-images.githubusercontent.com/104556686/168206925-4f8922f0-c25b-4146-9a1f-44ad4cfccb13.png)

I found that the uri of `Material #15.jpg` is converted wrongly in the glTF file. 
![image](https://user-images.githubusercontent.com/104556686/168207102-892fb474-1cff-49f1-afc9-b84bea07851d.png)

After i change the image name to `Material.jpg`, the issue is solved. 
![image](https://user-images.githubusercontent.com/104556686/168207387-7a27fe3a-3431-4a09-a626-e3ba39eadc88.png)

I think the problem is related to the character `#` inside the image name. Due to i cannot control the naming of image, are there any other solution to prevent this issues instead of rename the value? 

Thanks!!

**Comment by clausnagel** [comment]
@chantelYiu, please provide a dataset for testing and reproducing the issue. Thanks.

**Comment by chantelYiu** [comment]
Thanks, @clausnagel 
To reproduce the issue, we can use the `Railway_Scene_LoD3` sample data. 
I renamed the image of water to `Water_Sparkling#.jpg`. 
![image](https://user-images.githubusercontent.com/104556686/168248488-7b130cdd-5b37-4ca4-9793-ac7c296cd9b6.png)
![image](https://user-images.githubusercontent.com/104556686/168248689-c387b2f4-d4e3-4a7d-b3f5-2811c3bb9884.png)

After VIS export, we can see that the water image cannot show with error "Failed to load image". 
![image](https://user-images.githubusercontent.com/104556686/168249303-9fef7207-67d0-4ade-a19d-efbbaff2fc83.png)

Testing dataset:
[Railway_Scene_LoD3.zip](https://github.com/3dcitydb/importer-exporter/files/8685698/Railway_Scene_LoD3.zip)

Thanks a lot!!

**Comment by clausnagel** [comment]
Fixed with #254. The fix will be available in the upcoming 5.2 release.
