### ISSUE TITLE
Possible import different EPSGs?

### ISSUE THREAD

**Issue by strech345** [3dcitydb/importer-exporter#26]
It's possible to use a geographic Projection (4326) for a Project and then to load different projected citygml files?
For example i have different epsgs for germany (25832, 25833,...) and want to load whole germany or europe or the whole world.

**Comment by rchr** [comment]
Generally it is not recommended to import a CityGML dataset defined in EPSG:4326 into the 3DCityDB. See [this comment](https://github.com/3dcitydb/importer-exporter/issues/16#issuecomment-251625216) for further information.

In addition, you need to specify one coordinate reference system (CRS) per 3DCityDB instance. This CRS is used for the geometry columns of the database. That means, there is only one CRS per 3DCityDB instance. Hence, it is not recommended to load CityGML datasets defined in different CRS into one database.

**Comment by FxKu** [comment]
With the new [v4.0 release](https://github.com/3dcitydb/importer-exporter/releases/tag/v4.0.0) it's possible to create multiple schemas of a 3DCityDB within one database under PostgreSQL, where each schema can have a different EPSG code. When using the `CREATE_SCHEMA` script a new database schema is created with the same CRS than the `citydb` schema. You then have to change the CRS using a database procedure `change_schema_srid` or more easily with the new Importer/Exporter. Still, we do not allow mixing CRSes inside one schema.
