### ISSUE TITLE
Automatic BBox calculation for tiling

### ISSUE THREAD

**Issue by BWibo** [3dcitydb/importer-exporter#265]
This feature request is related to https://github.com/3dcitydb/importer-exporter/issues/178.

Currently, the extent for tiling has to be computed by the user beforehand.
It would be nice, if there was an option for tiling to compute the BBox automatically, e.g. based on the extent of all features returned after all other filter criteria have been applied, e.g.:

* No filter criteria have been applied: BBox including all features in DB.
* Filter criteria have been applied: BBox including all features returned by the applied filters.

For instance, this would simplify XML queries:

```xml
<!-- Now -->
 <tiling>
    <extent srid="4326">
      <lowerCorner>11.33533801319881 48.06338604481738</lowerCorner>
      <upperCorner>11.74844020344211 48.25231661323132</upperCorner>
    </extent>
    <rows>10</rows>
    <columns>10</columns>
  </tiling>

<!-- With auto BBox computation -->
<tiling>
    <rows>10</rows>
    <columns>10</columns>
</tiling>
```

**Comment by clausnagel** [comment]
Will not be resolved for version 5.x of the Importer/Exporter. We should revisit it for the next major version 6.0.
