### ISSUE TITLE
VIS Export and KML Export

### ISSUE THREAD

**Issue by Ferkelcode** [3dcitydb/importer-exporter#266]
Hello,

I am following the tutorial to learn KML/COLLADA/glTF Export, but my Importer-Exporter only has VIS export, what is the difference between these two? How can I have KML export?

Thanks!

**Comment by clausnagel** [comment]
The tutorial is based on an older version of the Importer/Exporter. The `KML/COLLADA/glTF Export` tab has been renamed to `VIS Export` in the meantime, but this change is not yet reflected in the tutorial. Although the UI elements have been rearranged and updated, the functionality of the `VIS Export` remains the same and you can still use it to do a KML export. Please refer to our [user manual](https://3dcitydb-docs.readthedocs.io/en/version-2022.1/impexp/export-vis.html) in addition to the tutorial.
