### ISSUE TITLE
URL for web map

### ISSUE THREAD

**Issue by Ferkelcode** [3dcitydb/importer-exporter#267]
Hello,

I saw the tutorial says that we could transfer spreadsheet and .KML file into URL with google Fusion Tables, but Fusion Tables is not working now. Do you know if there is another way to get the URL?

Thank you.

**Comment by BWibo** [comment]
You can use GoogleSpreadsheets instead, as described here: 
https://3dcitydb-docs.readthedocs.io/en/latest/webmap/online-spreadsheet.html
