### ISSUE TITLE
Errors on importing CityGML models generated by FME

### ISSUE THREAD

**Issue by zhangjw5** [3dcitydb/importer-exporter#27]
Hi,
I am writing my graduation thesis, "Based on CityGML 3DGIS Application Studies", I use the 3DCityDB Importer Exporter tool to import my own CityGML data into the 3DCityDB database, but it is wrong to show Failed to resolve XLink reference '# fme-gen-3010b1e6 -9537-4a87-8e67-f72ebcf0b4f3 ', I feel very depressed, how can I do?
Best Regards,
Jingwen

**Comment by clausnagel** [comment]
Your dataset contains an `xlink:href` reference to an object with a `gml:id` of value `fme-gen-3010b1e6-9537-4a87-8e67-f72ebcf0b4f3`, but there is no such object in the dataset. Thus, the reference cannot be resolved and consequently no data can be imported.

This seems to be a data issue in the first place. Please fix your dataset.

**Comment by FxKu** [comment]
Ha, Claus was faster :)
- Are there whitespaces in your XLink target ID. I see at least three? Maybe this causes the problem.
- Which version of the 3DCityDB and FME (?) you are using?

**Comment by zhangjw5** [comment]
Thank you for the enthusiastic help, 
my citygml data is converted by the BIM data through the FME tool, when I use the FME tool to view the CityGML data, the display of gml_id can not be found in the file, import to 3DcityDB gml_id is also different.
When I see my original data, did not find XLink target ID have the space,
3DCityDB version is 3.3.0, FME version is 2017.0.0.2

**Comment by zhangjw5** [comment]
This is part of my data and FME display:
![data](https://cloud.githubusercontent.com/assets/28328895/25700838/0e237dfe-30fc-11e7-9566-65c9f7ef713a.png)
![fme](https://cloud.githubusercontent.com/assets/28328895/25700850/18c810c6-30fc-11e7-83c5-2ceb139e6347.png)

**Comment by clausnagel** [comment]
@zhangjw5 can you share your CityGML file for testing?

**Comment by zhangjw5** [comment]
Thanks for your reply, 
Of course, this is my experimental data.
http://pan.baidu.com/s/1o7D3GU2

**Comment by clausnagel** [comment]
Thanks for sharing your dataset.

The dataset contains a lot of `gml:MultiGeometry` elements. CityGML supports the use of `gml:MultiGeometry` at few places, for instance, as geometry for `gen:GenericCityObject` or `grp:CityObjectGroup` features. So the dataset validates against the CityGML schema.

However, the 3DCityDB lacks support for `gml:MultiGeometry`. That's why the geometry is not imported and why XLink references cannot be resolved. The latest version 3.3 of the Importer/Exporter logs a corresponding error message when importing your dataset:

> [16:20:35 ERROR] GENERIC_CITY_OBJECT 'UUID_cbed4c39-917f-4e5b-b4b1-c39e7a138862': Unsupported geometry type MULTI_GEOMETRY.

To solve this issue, you have to change your FME process to write another geometry type such as `gml:MultiSurface` instead of `gml:MultiGeometry`.

**Comment by zhangjw5** [comment]
Yes, thank you very much!
I tried to import another model and successful, and export the gml file is also open.
However, there have a new question: when I export the date for KML / glTF, it exports nothing.
Then I checked the column ENVELOPE of the table CITYOBJECT,
It is null, I tryed and recalculateed all values using the Importer / Exporter tool,but it did not work.
What should I do?
I have a little bit of puzzles that I import into the database that many properties are null, but exporting the CityGML model in the FME view is correct.
This is my data:http://pan.baidu.com/s/1slxyXCL
![1](https://cloud.githubusercontent.com/assets/28328895/25837764/e846caa4-34c1-11e7-988d-b19d4d77eb30.png)

**Comment by yaozhihang** [comment]
I have tested the KML/glTF export of your shared data using both Oracle and PostGIS databases. Everything worked fine on my machine. 

A successful KML/glTF export requires a number of parameter settings which are explained in detail in the [3DCityDB documentation](http://www.3dcitydb.org/3dcitydb/fileadmin/downloaddata/3DCityDB_Documentation_v3.3.pdf). For a quick start, a step-by-step [hands-on tutorial](http://www.gis.bgu.tum.de/fileadmin/w00bov/www/Dokumente/Projekte/3DCityDB/3DCityDB_V3.3_Hands-On_Tutorial.pdf) is very helpful.

![1](https://dl.dropboxusercontent.com/u/69071139/georesglTF.png)

**Comment by zhangjw5** [comment]
Thanks, listen to your suggestion, I once again read the document carefully and try again,
I think maybe because of my SRID set up a problem, so it's shown like this:
![2](https://cloud.githubusercontent.com/assets/28328895/25886093/a294a814-358e-11e7-88fc-cfb29bf2a4ce.jpg)
This is my SRID and URN settings:
![1](https://cloud.githubusercontent.com/assets/28328895/25886140/d40610c2-358e-11e7-8f21-2a87bed6df49.png)
GML file is set as follows:
![3](https://cloud.githubusercontent.com/assets/28328895/25886212/2c03ab18-358f-11e7-89d5-a46a854796bd.png)

**Comment by FxKu** [comment]
Hey,
so your file has the SRS 25833 and your 3DCityDB has 31467? Well, this does not fit together. You can change the database's SRID with the stored procedure change_schema_srid (see documentation - only update metdata - do not transform the coordinates as they are 25833). Then buildings should be placed correctly (only if the source data is correctly referenced, of course).
Cheers

**Comment by zhangjw5** [comment]
I am very sorry, this is my mistake, I figure the wrong data, in fact, the data screenshots are like this:
![111](https://cloud.githubusercontent.com/assets/28328895/25902799/265131b6-35cd-11e7-9e3f-70697b009d65.png)
Looking forward for your reply, thank you！

**Comment by zhangjw5** [comment]
Hi,
I found the problem is not SRID, which is due to Google Earth's 3D building display simulation shows the problem.
Data export KML format still can not show, although I have all the models involved in the building properties are set, but still useless. I hope you can get your guidance, what should I do?
![building](https://cloud.githubusercontent.com/assets/28328895/25985544/93dd71c6-371d-11e7-9030-709b30f7c680.png)
![export](https://cloud.githubusercontent.com/assets/28328895/25985545/9404f188-371d-11e7-9291-76690a2b51f4.png)
![kmlexport](https://cloud.githubusercontent.com/assets/28328895/25985546/94512f26-371d-11e7-9f86-829cc6faeb5a.png)
![landuse](https://cloud.githubusercontent.com/assets/28328895/25985547/949f4a08-371d-11e7-9305-21e3c29794a1.png)

**Comment by yaozhihang** [comment]
Make sure that the parameters on the Altitude/Terrain panel are set as follows:
![1](https://dl.dropboxusercontent.com/u/69071139/tmp/Clipboard01.png)

Run the KML export again and load the exported KML files into Google Earth Pro. You also need to disable the Google Earth's "Terrain" and "3D buildings" layers

**Comment by zhangjw5** [comment]
Thank you very much,
I tried again and again, the result is:
![result](https://cloud.githubusercontent.com/assets/28328895/25991560/24da6504-3736-11e7-883c-f0bdb70e2fed.png)
And I tried another way and the result was wrong:
![error](https://cloud.githubusercontent.com/assets/28328895/25991580/43c63682-3736-11e7-8bbf-5599f5c1ec42.png)
What method can I use to correct the model？

**Comment by LoveNile** [comment]
I also encountered the same problem,would you solve it?

**Comment by zhangjw5** [comment]
Sorry, I can not give you the right advice, although the exported KML file is like this, but I tried to open the file in 3dcitydb-web-map, the result is like this：
![22222](https://cloud.githubusercontent.com/assets/28328895/26023601/792cdc7e-37f2-11e7-8f08-f24432d2b13d.jpg)

**Comment by rezamolkara** [comment]
Hi everybody
I have problem to export to citygml.
I use FME and my data is shp.
When I import my gml data to 3DCityDB it says valid but when I port data to kml it was rong in shape and location. My coordinate system is WGS 84 , UTM  SIRD 4326.

When I import data to 3DCityDB it imports data but show this warning:
[10:41:39 WARN] gml:LINEAR_RING (unknown gml:id): Linear ring is not closed. Appending first coordinate to fix it.

this is my data:
![gmldata](https://cloud.githubusercontent.com/assets/25344949/26023627/5e21113a-37c9-11e7-9ce2-b7dc237ef6fd.png)
![gml scoordinate](https://cloud.githubusercontent.com/assets/25344949/26023718/57b1128a-37cb-11e7-8a52-2ab46237223b.png)

But in the 3DCityDB it shows my boundaries coordinate like this:
![dtatacoords3dcitydb](https://cloud.githubusercontent.com/assets/25344949/26023663/040d543c-37ca-11e7-92b0-bbf19e7eae00.png)
And the exported data to kml is like this:
![kmlresult1](https://cloud.githubusercontent.com/assets/25344949/26023704/fa21ed1a-37ca-11e7-9de6-eabfe2dabe00.png)
![kmlresult2](https://cloud.githubusercontent.com/assets/25344949/26023705/ff53a972-37ca-11e7-8be2-c818d1629f75.png)
 
Any body help me?

**Comment by rezamolkara** [comment]
I solved it gays.
![image](https://cloud.githubusercontent.com/assets/25344949/26029175/9aefa054-3837-11e7-96f1-5e7e3596997a.png)
Thank U;-)

**Comment by rezamolkara** [comment]
Hi gays,
I have problem by importing building gml format to 3DCityDB.
This is my data:

[CevreSelected1.txt](https://github.com/3dcitydb/importer-exporter/files/1007817/CevreSelected1.txt)
It's shows this error:

[14:17:47 ERROR] BRIDGE_WALL_SURFACE 'GML_': Skipping import since this is not a top-level feature type. 3dcitydb

Thanks.

**Comment by FxKu** [comment]
Forgot about this one. As the log message said, you got features in your data which are encoded as top-level feature, but by the CityGML schema they are not. In your case, you are missing the bridge.

Incorrect:
`<core:cityObjectMember>
  <bridge:WallSurface ...
  ... wall attributes
  </bridge:WallSurface>
</core:cityObjectMember>`

Correct:
`<core:cityObjectMember>
  <bridge:Bridge ...
  ... bridge attributes
    <bridge:boundedBy>
      <bride:WallSurface ...
      ... wall attributes
      </bride:WallSurface
      ... more walls, roofs etc. to come here
    </bridge:boundedBy>
  </bridge:Bridge>
</core:cityObjectMember>`

Hope this can help you. How did you create the CityGML file, btw?

**Comment by rezamolkara** [comment]
Hi sir

Thank you for yor answering.
I used FME Desktop.
If it possible say me how can I make true CityGML 3D format.
By which software.

Best regards.

**Comment by FxKu** [comment]
You can use FME for that. I'm not familiar with it, but it seems you just forgot to add the bridge feature. Should be easy to fix.

**Comment by kesai** [comment]
Any body tell me how to create citygml by fme,my 3d model data format is obj.when i use fme to export gml,it cannot import to 3dcitydb,the error is:GENERIC_CITY_OBJECT 'UUID_cbed4c39-917f-4e5b-b4b1-c39e7a138862': Unsupported geometry type MULTI_GEOMETRY.and i don't know how to use fme fix it.

**Comment by FxKu** [comment]
This is a well known issue :)
Please, take a look at issue #28

**Comment by kesai** [comment]
Thanks,now i can import data to citydb,but when i export it as gltf and load it by google earth,it displays discorrect.see the picture below.
![error](https://user-images.githubusercontent.com/5986940/27718810-e5f70ede-5d80-11e7-83e8-2ad03047f680.jpg)

**Comment by yaozhihang** [comment]
Could you open your CityGML dataset using FME Data Inspector and check, if the same rendering problem also occur?

**Comment by kesai** [comment]
Yes,i create models from cityengine,then use fme and convert it to citygml,it may aslo discorrect in fme.how to solve it.thx!

**Comment by FxKu** [comment]
To me, it looks like the order of ordinates is somehow flipped ... so not XYZ but ZYX or ZXY. I think, there is a transformer in FME to change the order of ordinates.

**Comment by kesai** [comment]
thank you ,i have solved it.it works good .but my citygml is different from the sample data,may lack some settings in fme ,can you give a example about how to use fme to create citygml ？

**Comment by clausnagel** [comment]
Maybe the FME 3D Solution Templates are a good starting point: http://www.virtualcitysystems.de/en/news/480-3d-solution-templates-now-available-in-the-fme-hub

**Comment by kesai** [comment]
Thanks,I have another problem.i created models by city engine,and then use fme to convert it to citygml,then import the citygml data to citydb,and next i export it to kml/gltf,everything looks so good.but when i loaded my data in the browser,the models are a little bigger than the orignal one.my coordinate system is 3847,the src info settings in citydb like this:
first:3857
second:urn:ogc:def:crs,crs:EPSG::3857,crs:EPSG::115700
what's wrong?

**Comment by anwar1010** [comment]
When Set Geo-location in SketchUp and then I convert SketchUp file using FME desktop. it cannot add a coordinate system in XML or GML file. Because of the coordinate system, I am unable to import or export data using 3DCity DB importer-exporter


this is the FME for SketchUp to XML converter file for lod3.
@clausnagel 

[skp2citygml_v1222.2 (backup).zip](https://github.com/3dcitydb/importer-exporter/files/1734526/skp2citygml_v1222.2.backup.zip)

**Comment by Waji504** [comment]
Hi,
I am working on my graduation  final year project , "Based on CityGML 3DGIS Application Studies", I use the 3DCityDB Importer Exporter tool to import my own CityGML data into the 3DCityDB database, but it is wrong to show Failed to resolve XLink reference '# fme-gen-72e95666-c183-4dbf-a9cb-2fb8ebfe17ad', I feel very depressed, how can I debug such type of errors ?
Best Regards,
Wajid Ali

**Comment by FxKu** [comment]
Hi Wajid,
Please, check our comments in this thread as your error report sounds "exactly" like the first post. If this does not help, you can still share a sample dataset so that we can reproduce the error and provide help. But, I'm sure you can already solve on your own if you reed the comments such as: 

> To solve this issue, you have to change your FME process to write another geometry type such as gml:MultiSurface instead of gml:MultiGeometry.

Good luck.

**Comment by Waji504** [comment]
Sir,
DO you have any documentation where all the process of  creating sketch up model and make a citygml  through (citygml2citygml_coordinateSystemChange.fmw) file and import it on the db importer exporter.

**Comment by FxKu** [comment]
Not really, sorry. See issue #34 where we gave some hints on converting SketchUp models.

**Comment by clausnagel** [comment]
If the XLink reference cannot be resolved, then either the referenced object does not exist in your dataset or the reference itself is bad (at least there shouldn't be a blank after the hash). As @FxKu wrote we can check your dataset if you share it. 

For questions and bugs related to Sketchup or FME processes, please contact the corresponding support teams.

**Comment by FxKu** [comment]
Dear @anwar1010 . This issue has been closed already. Please open a new one referring to the bounding box "error" and I will provide an answer :)
