### ISSUE TITLE
Installation issue on mac

### ISSUE THREAD

**Issue by alsino** [3dcitydb/importer-exporter#283]
Hi there,

this might be a noob question, but I am having problems when installing the 3dcitydb Importer/Exporter on my mac. After having downloaded the latest release [here](https://github.com/3dcitydb/importer-exporter/releases/download/v5.3.0/3DCityDB-Importer-Exporter-5.3.0.zip), I can run the "3DCityDB-Importer-Exporter" executable which starts the Importer/Exporter GUI. 

However the [GUI setup wizard](https://3dcitydb-docs.readthedocs.io/en/release-v4.3.0/first-steps/install-impexp.html#gui-setup-wizard) does not start and I also do not see an installation directory with the required shell scripts to set up teh PostGres database connection.

What am I doing wrong? Any help appreciated. Thanks a lot!

**Comment by clausnagel** [comment]
Follow the installation steps as outlined in the latest version of the [3DCityDB online user manual](https://3dcitydb-docs.readthedocs.io/en/version-2022.2/first-steps/index.html). As mentioned there, download the GUI installer from [here](https://github.com/3dcitydb/3dcitydb-suite/releases).

**Comment by alsino** [comment]
Ok, this was helpful thanks, as I previously did not install the entire 3D City Database Suite. Thanks!
