### ISSUE TITLE
NoClassDefFoundError: org/citydb/gui/plugin/view/ViewExtension when running the Importer/Exporter CLI

### ISSUE THREAD

**Issue by spechtx** [3dcitydb/importer-exporter#285]
Describe the bug:
When attempting to use the Importer/Exporter command line interface (version 5.3.0), a java.lang.NoClassDefFoundError is thrown with the message org/citydb/gui/plugin/view/ViewExtension.

To Reproduce:

Run the following command:

`java -jar lib/impexp-client-cli-5.3.0.jar import --duplicate-log=/mnt/data/temp/3dcitydb/duplicate.log --import-log=/mnt/data/temp/import.log --input-encoding=utf-8 --log-file=/mnt/data/temp/3dcitydb/logfile.log --log-level=info --import-mode=import_all --worker-threads=16 --db-type=postgresql --db-host=localhost --db-port=5434 --db-name=3DCITYDB --db-schema=citydb --db-username=***** --db-password=***** /mnt/data/temp/3dcitydb/hh/`

See error:
```
[12:22:15 INFO] Starting 3D City Database Importer/Exporter, version 5.3.0
[12:22:15 INFO] Loading plugins
Exception in thread "main" java.lang.NoClassDefFoundError: org/citydb/gui/plugin/view/ViewExtension
```

Expected behavior:
The Importer/Exporter should start and load the plugins without any exceptions.

Environment (please complete the following information):

OS: Ubuntu Server 22.04
Java version: OpenJDK 11
Database: PostgreSQL 15]

**Comment by spechtx** [comment]
I was able to start the import when using clinent-gui instead of client-cli:
`java -jar lib/impexp-client-gui-5.3.0.jar`

**Comment by spechtx** [comment]
Workaround:
Interestingly, when running the command with the client GUI, instead the CLI, the import proceeds without any issues:
`java -jar lib/impexp-client-gui-5.3.0.jar import --duplicate-log=/mnt/data/temp/3dcitydb/duplicate.log --import-log=/mnt/data/temp/import.log --input-encoding=utf-8 --log-file=/mnt/data/temp/3dcitydb/logfile.log --log-level=info --import-mode=import_all --worker-threads=16 --db-type=postgresql --db-host=localhost --db-port=5434 --db-name=3DCITYDB --db-schema=citydb --db-username=***** --db-password=***** /mnt/data/temp/3dcitydb/hh/`

This is unexpected, as I am working in a shell environment and should not require the GUI version to run the import.

**Comment by clausnagel** [comment]
Seems like you have a plugin in your `plugins` folder that requires a GUI. Delete the plugin from the `plugins` folder to prevent it from being loaded at startup.

Btw, I would recommend to start the CLI using the `impexp` executable in the `bin` folder rather than using the `lib/impexp-client-gui-5.3.0.jar` directly.

**Comment by spechtx** [comment]
Thank you very much for your helpful reply! It makes sense that a plugin requiring a GUI could have caused the issue when using the CLI. Turns out, I was following some older documentation, which is where I got the lib folder usage from...

Have a nice day!

**Comment by clausnagel** [comment]
Added proper log messages in case a plugin cannot be loaded through #287
