### ISSUE TITLE
Problem with importing all features into the database.

### ISSUE THREAD

**Issue by michaelknave** [3dcitydb/importer-exporter#29]
I have .gml file I want to import to the database. This dataset consist of more features (Relief, Building, TrafficArea, PlantCover,...). Validation is fine. But after import, just Building class is imported a none of the other classes.

**Comment by FxKu** [comment]
As said in my mail, if you 
- have used the feature class filter of the Importer/Exporter correctly (= selected all classes)
- and you did not receive any warning or error messages
it is hard for us to tell, what went wrong.

I suspect some issues with your CityGML file. Have a close look at it again and if you are not sure if everything is correct, please send us a sample file. Just one test object of a feature class, that is not imported.

**Comment by FxKu** [comment]
Closing this issue as @michaelknave reported to me on Twitter (07.06.2017):
"Well. Finally I have found out that there was mistake on my side in conversion itself. The structure was not right so it did not recognized the features ..."
