### ISSUE TITLE
Problem with citygml file validation

### ISSUE THREAD

**Issue by elainegv** [3dcitydb/importer-exporter#290]
Dear
I have a problem importing the CITYGML file in LOD 3.
When I perform the import and validation the following error appears:
ERROR] Invalid content at [30568, 17]: cvc-complex-type.2.4.a: error with element 'bldg:boundedBy'.
Does anyone know what it could be and how I can fix it?
Thank you very much in advance.

![image](https://github.com/3dcitydb/importer-exporter/assets/142768783/fd2b6887-ab6f-4267-bdd5-c96aaa6e0bdf)
![erro_LOD3](https://github.com/3dcitydb/importer-exporter/assets/142768783/b78d365c-083e-4982-9775-454badd3cbbf)

**Comment by elainegv** [comment]
Thank you very much for your help.
Here is part of my file.
I tried to send the zip file itself but it didn't allow me.
[erro_xml.docx](https://github.com/3dcitydb/importer-exporter/files/12395492/erro_xml.docx)
![erro_xml](https://github.com/3dcitydb/importer-exporter/assets/142768783/fee9b109-0d15-48af-8beb-e6a0d1a07941)

**Comment by clausnagel** [comment]
Thanks, @elainegv, for sharing the dataset.

The reason for the validation error is simple: The dataset contains three `BuildingFurniture` objects (at lines 30567, 83014, and 103570) that have nested `WallSurfaces`. However, in CityGML 2.0 it is not allowed for objects of type `BuildingFurniture` to have boundary surfaces. This is also the reason why the XML validation of the Importer/Exporter complains about the invalid `bldg:boundedBy` elements.

To fix the problem, remove these `WallSurfaces` and store the geometry using only the `bldg:lod4Geometry` property of `BuildingFurniture`. It seems that you are using the 3DIS CityGML Sketchup Plugin to model the data? I have not used this tool before, but maybe you created the `WallSurfaces` for the `BuildingFurniture` objects manually and can simply remove them? Or maybe it's a bug of the tool. Either way, I recommend contacting 3DIS support for further assistance.

Interestingly, there is a fourth `BuildingFurniture` object (at line 49230) that has no `WallSurfaces`, only a `bldg:lod4Geometry` geometry. This `BuildingFurniture` object is valid any can server as template for fixing the others. I recommed changing the geometry type from `gml:MultiGeometry` to `gml:MultiSurface`.

Hope this helps.
