### ISSUE TITLE
When using the CLI import options, can I specify that it should update?

### ISSUE THREAD

**Issue by sigurdbengtson** [3dcitydb/importer-exporter#291]
I Import to 3D city DB via the CLI functions, using `impexp import `. Is there an option to make it so that any matching rows are updated? It seems I just add more rows when importing from a dir from which I've import previously. I.e. I end up with duplicate rows in my database.

**Comment by clausnagel** [comment]
https://3dcitydb-docs.readthedocs.io/en/version-2022.2/impexp/cli/import.html

Check documentation of `import mode`. Alternatively, consider creating an `import log` together with an `import list` filter.
