### ISSUE TITLE
VC Database

### ISSUE THREAD

**Issue by cbsemre** [3dcitydb/importer-exporter#296]
merhabalar.
VC Database ımporter/exporter versiyon 5.0.2 kullanıyorum
[17:36:45 ERROR] Caused by: org.citydb.core.operation.importer.CityGMLImportException: Failed to find an ADE extension for the ADE table 'cityobject'.
citygml verilerini import ederken hata alıyorum. yardımcı olabilirmisiniz.. 

/// **

Hello.
VC Database import/exporter version 5.0.2 tool
[17:36:45 ERROR] Cause: org.citydb.core.operation.importer.CityGMLImportException: No ADE extension found for ADE table 'cityobject'.
I'm getting an error when importing citygml files. you can help..

**Comment by clausnagel** [comment]
We do not provide support for VCS products like the VC Database here. Please contact the VCS support.

**Comment by clausnagel** [comment]
WFS-related issues should be posted in the WFS repository issue tracker: https://github.com/3dcitydb/web-feature-service/issues

In order to be able to help you, please open a new issue there and add more information:
1. What version of the 3DCityDB are you using?
2. What version of the WFS are you using?
3. What is the exact query that you have sent to the WFS?
4. Please provide the config.xml of your WFS
5. Please provide an excerpt of the dataset that you loaded into the 3DCityDB

**Comment by cbsemre** [comment]
1. 3D City Database: 4.0.0
2. DBMS: PostgreSQL 16.0
3. 3D City Database ımporter/exporter 5.4.0
4. 3DCityDB-Web-Feature-Service-4.3.0

**Comment by cbsemre** [comment]
![image](https://github.com/3dcitydb/importer-exporter/assets/105004541/18d6a60c-b962-4bb0-b6b5-42264bc88b5d)

**Comment by cbsemre** [comment]
![image](https://github.com/3dcitydb/importer-exporter/assets/105004541/a6ce704f-b281-4eb1-988c-fa6a71722592)
### My 3d citygml data is available in the database

**Comment by cbsemre** [comment]
v5.0.0 Can I make instant queries with ?
In the release notes it shows that I can
Support for ad-hoc queries and stored queries.
Additionally, new WFS operations and processes have been added, such as stored query management, as well as new query results such as pagination and sorting. We would like to thank Virtual City Systems for their contributions.GetPropertyValue

**Comment by cbsemre** [comment]
Which version do I need to use to make instant queries with wfs?

**Comment by clausnagel** [comment]
Well, based on my previous answer, all WFS releases >= 5.0.0 support ad-hoc queries. As written above, I recommend using the latest release.

**Comment by cbsemre** [comment]
Thank you, I will edit my versions immediately and contact you again.

**Comment by cbsemre** [comment]
### http://localhost:8080/citydb-wfs/wfs
I distributed my war file. I think
  This time it doesn't read my config.xml file.
How can I solve this?
I distributed it with Apache Tomcat 9 version and it is in startup state.
![image](https://github.com/3dcitydb/importer-exporter/assets/105004541/024fe23e-88c2-49b2-920c-2f97484bc356)

**Comment by clausnagel** [comment]
Hard to say what is going wrong at your side. I recommend following the installation guide: https://3dcitydb-docs.readthedocs.io/en/latest/wfs/index.html

**Comment by cbsemre** [comment]
Hello.
When I remove the database connection (picture above) in my config.xml file, my wfs service works.
But when I connect to the database, it does not work. It gives the error (http status 500 - internal server error).
Can you help me with this

**Comment by BWibo** [comment]
As written in the error message, your request is missing the mandatory REQUEST parameter. The WFS standard is documented here: https://www.ogc.org/standard/wfs/

**Comment by cbsemre** [comment]
There is no error when it appears in xml page in wfs service.
But when I make database connection settings in my config.xml file, I cannot connect to the wfs service.

**Comment by clausnagel** [comment]
This does not make sense. The error message in your screenshot will only be sent if the database connection has been successfully established. Otherwise, the service will already fail with a message saying that the database connection could not be established.

Changes to the config.xml require to reload the WFS service (e.g. through the Tomcat Manager application when using Tomcat).

**Comment by cbsemre** [comment]
![image](https://github.com/3dcitydb/importer-exporter/assets/105004541/1f233bd0-42ac-4b19-82fa-a0f5be8fd6a7)
### Can you help me more clearly with my problem regarding wfs?
Why can't I find the data I have in my database?

**Comment by clausnagel** [comment]
Please make sure to read the documentation. The WFS only supports querying top-level feature types: https://3dcitydb-docs.readthedocs.io/en/latest/wfs/functionality/basic.html#citygml-feature-types

Either your gml:id does not belong to a top-level feature type or there is no corresponding gml:id in your database.

**Comment by cbsemre** [comment]
all right. If Citygml supports high-level feature types;
How do I set the gml:id property or any property in my citygml data that I want to query as top-level?

**Comment by cbsemre** [comment]
https://3dcitydb-docs.readthedocs.io/en/latest/wfs/index.html

I couldn't find the top level setting for the data I wanted to query in this document.

**Comment by cbsemre** [comment]
![image](https://github.com/3dcitydb/importer-exporter/assets/105004541/4f0de6f7-5031-45ad-aef8-6e079f151d91)
### It is stated that my building data will be queried in this section.

**Comment by cbsemre** [comment]
very interesting...
Everything looks great, but it cannot find the data in the database.
I can't get results

**Comment by clausnagel** [comment]
Why don't you simply ask the service to return the first building in the database for testing purposes?

```xml
<wfs:GetFeature service="WFS" version="2.0.0"
  xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:fes="http://www.opengis.net/fes/2.0"
  xmlns:bldg="http://www.opengis.net/citygml/building/2.0" count="1">
  <wfs:Query typeNames="bldg:Building"/>
</wfs:GetFeature>
```

**Comment by cbsemre** [comment]
![image](https://github.com/3dcitydb/importer-exporter/assets/105004541/a47109cf-05c5-478f-ae12-352e1f640241)
### error: citydb object does not exist
evet sanırım bina verim etkin değil ve ondan dolayı sonuç alamıyorum

**Comment by cbsemre** [comment]
![image](https://github.com/3dcitydb/importer-exporter/assets/105004541/0b5b34b5-a9b9-4348-93e9-fa8e3f6dfa88)

**Comment by cbsemre** [comment]
![image](https://github.com/3dcitydb/importer-exporter/assets/105004541/5b5f52e8-5725-4b40-9990-948cd53f7ca5)

### I placed it. But I am getting an object error in the query section.
  building selected as object###
