### ISSUE TITLE
Bug in About link

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/importer-exporter#299]
Hi!

Tiny bug, at least in version 5.4.2 of the Importer/Exporter used in Ubuntu 22.04.
When you are in the About menu and click on the link to

"Get in touch with us on http://github.com/3dcitydb"

Something goes wrong, as in the Importer/Exporter console there are errors.
Same thing happens when you click on the urls of the Partners.

![image](https://github.com/3dcitydb/importer-exporter/assets/15018017/aab66040-c519-4bdc-8b33-5e7f7d016c5d)

**Comment by clausnagel** [comment]
Unfortunately, there is not much we can do about this. The Java functionality we use for opening a URL in the default web browser of the OS works nicely under Windows but sometimes lacks support under Linux. Well, but I tested with Ubuntu 24.04 and it worked fine for me (I used Firefox as default web browser). At least I improved the error handling. The error is now caught and the user is advised to use his/her favorite web browser to open the URL instead.
