### ISSUE TITLE
import citygml

### ISSUE THREAD

**Issue by FizrukBet** [3dcitydb/importer-exporter#3]
Hello, thanks for your work! 
I have some problem with import citygml file lod2.
I try to import the citygml lod2 file which is made in FME Desktop, but I have similar errors in console
log 
"BUILDING_WALL_SURFACE 'fme-gen-4333644a-d071-46f6-a850-769f245feaa6': Skipping import since this is not a top-level feature type"

maybe you advise me better way to create citygml file.

![image](https://cloud.githubusercontent.com/assets/10652308/8208059/011aa77e-150e-11e5-8615-136c1e46c8c6.png)

https://drive.google.com/file/d/0B88PO_XBwUZIX3RHTHduLXhKUTg/view?usp=sharing

**Comment by clausnagel** [comment]
For every building in your scene, you should create a separate ```<Building>``` element in your dataset. The ```<WallSurface>s```, ```<RoofSurface>s``` and ```<GroundSurface>s``` describing the outer shell of a single building should then be modelled as nested child elements of the ```<Building>``` element representing that building.

The use of ```<GroundSurface>``` in your dataset is not correct. A ```<GroundSurface>``` is meant to represent the ground plate of a single building. You rather use it to model the terrain of your scene. For this purpose, CityGML provides the ```<ReliefFeature>``` feature.

Please check out this official CityGML example: http://schemas.opengis.net/citygml/examples/2.0/building/Building_LOD2-EPSG25832.gml

It only contains a single building, but shows how to model the boundary surfaces as child elements. And it also demonstrates the use of ```<ReliefFeature>```.

Have fun :-)

**Comment by FizrukBet** [comment]
many thanks!

**Comment by clausnagel** [comment]
You are welcome. Please re-open if you still get errors after having changed the structure of your dataset.
