### ISSUE TITLE
ERROR: geometry requires more points

### ISSUE THREAD

**Issue by Krassnig** [3dcitydb/importer-exporter#301]
Hello,

I was trying to import CityGML files of Brandenburg and one of the files threw an error.
I'm not sure if it is an error in the CityGML file or the import process.

I got the file from https://data.geobasis-bb.de/geobasis/daten/3d_gebaeude/lod2_gml/lod2_33351-5791.zip
and used the importer-exporter tool, no settings changed (Version 5.4.0 on Windows 10).
The other CityGML files in https://data.geobasis-bb.de/geobasis/daten/3d_gebaeude/lod2_gml/ import perfectly fine.

The File:
[lod2_33351-5791.zip](https://github.com/3dcitydb/importer-exporter/files/14294400/lod2_33351-5791.zip)

Console Output:
[console_output.txt](https://github.com/3dcitydb/importer-exporter/files/14294403/console_output.txt)

The error thrown says "Caused by: org.postgresql.util.PSQLException: ERROR: geometry requires more points"
I'm not sure if the geometry is correct or not.

Thank you for your help!

**Comment by clausnagel** [comment]
This is a data issue. For example, check line 15223 of your file. This line defines a `<gml:LineString>` with just one point. However, a linestring must consist of at least two points, of course.

**Comment by Krassnig** [comment]
Thank you very much! I will contact geobasis-bb about this.
