### ISSUE TITLE
CityJSON 2.0 support

### ISSUE THREAD

**Issue by wlinna** [3dcitydb/importer-exporter#303]
Hello,

according to README.md, CityJSON 1.0 is supported. However, in Nov 2023 CityJSON 2.0 was published and accepted as an OGC standard. In April 2024 2.0.1 was published. 

I think it'd make sense to implement support for it

**Comment by clausnagel** [comment]
CityJSON 2.0 will be supported by the next major version 5.0 of the 3DCityDB. The Importer/Exporter will be replaced by [citydb-tool](https://github.com/3dcitydb/citydb-tool) as database client for version 5.0. You can already download and test beta releases from [here](https://github.com/3dcitydb/citydb-tool/releases).

There are no plans to add support for CityJSON 2.0 in the current Importer/Exporter anymore.

**Comment by wlinna** [comment]
Okay. Thank you for the clarification. I suppose this issue can then be closed
