### ISSUE TITLE
Problems with ADE Manager and ADE with association class

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/importer-exporter#305]
Dear 3DCityDB team,

I am experiencing some issues using the ADE Manager to generate the SQL scripts of an ADE for CityGML 2.0 that I am developing.

**Goal**: (Taking inspiration from CityGML 3.0), I want to extend _CityObject with a "relatedTo" association. I'd prefer Option 1 (with relationType as CodeList), but, if not possible, I can live with Option 2 (relationType as string).

*Option 1*:
![image](https://github.com/3dcitydb/importer-exporter/assets/15018017/51e6d012-69a3-4567-a621-3bfecbe3dc52)

*Option 2*:
![image](https://github.com/3dcitydb/importer-exporter/assets/15018017/fd2f4e47-1874-4293-b31d-ac3d21b7a6c4)

**Problem**: When I try to generate the SQL scripts, the following happens:
- Option 1: an error is raised in the console. The SQL script is still generated, but generated association table is missing both *relationtype* and *relationtype_codelist* columns (this is what I'd expect, at least);
- Option 2: no errors are raised, but the generated table is the same as before (no *relationtype* column is generated).

I attach here a small, stripped-down (zipped) xsd file containing both these examples. Please uncomment either option accordingly.
[RelationType_ADE.zip](https://github.com/user-attachments/files/15865422/RelationType_ADE.zip)

**Questions**:
- Is there something wrong in the XSD?
- If not, is this an unsupported case of the ADE manager?
- Which solution/workaround do you suggest?

Thanks for your help!!

G.

Software:
- Importer/Exporter 5.4.3 shipped with 3DCityDB suite 2023.0.1

PS. Just FYI: when loading the XSD in FME 2023.x, no errors are raised and I can "see" the new ADE attributes as desired in both cases.

**Comment by clausnagel** [comment]
I guess your XML schema has issues and is not following GML rules. I will take a closer look.

**Comment by clausnagel** [comment]
You have to create a separate complex type for the association class. You can basically follow the rules for encoding association classes given in the "CityGML 3.0 Part 2: GML Encoding" standard: https://docs.ogc.org/is/21-006r2/21-006r2.html#association-classes-section. We also applied these rules to the mapping of the `relatedTo` association in CityGML 3.0.

Here is a working version of your schema: [RelationType_ADE.zip](https://github.com/user-attachments/files/16647272/RelationType_ADE.zip)

I manually adapted your schema. However, ShapeChange should be able to map association classes to intermediate complex types automatically.
