### ISSUE TITLE
Replace DOS paths in KML network links

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/importer-exporter#31]
When exporting to KML/COLLADA/glTF, the root KML file containing the network links to the generated tiles uses DOS paths as `<href>` reference:

```xml
<Link>
  <href>Tiles\0\0\kml_Tile_0_0_collada.kml</href>
  <viewRefreshMode>onRegion</viewRefreshMode>
  <viewFormat/>
</Link>
```
The backslashes should be replaced with normal slashes: `Tiles/0/0/kml_Tile_0_0_collada.kml`

**Comment by yaozhihang** [comment]
fixed in 79a1bbc3b5321d57b5f414165e1fb343b30f79c5
