### ISSUE TITLE
Missing core:creationDate from CityGML Buildings in citydb

### ISSUE THREAD

**Issue by Krassnig** [3dcitydb/importer-exporter#318]
Hello,

In the CityGML files of the Vienna dataset they store the date they scanned the building in the `<core:creationDate>` element.

```xml
	<core:cityObjectMember>
		<bldg:Building gml:id="UUID_LOD2_043491-77417aa2-b1be-4a0f-a605">
			<gml:name>043491</gml:name>
			<core:creationDate>2016-09-29</core:creationDate> <!-- can't find this one -->
			<gen:stringAttribute name="Blattnummer">
				<gen:value>078085</gen:value>
			</gen:stringAttribute>
			<gen:stringAttribute name="HoeheDach">
				<gen:value>210</gen:value>
			</gen:stringAttribute>
			<gen:stringAttribute name="HoeheGrund">
				<gen:value>206</gen:value>
			</gen:stringAttribute>
                        ....
```
Once I import this dataset into the 3dcitydb I can't find the creationDate.
I would assume this corresponds to the citydb.cityobject.creation_date but this is set to the date of the import.
![image](https://github.com/user-attachments/assets/8967c82e-7052-439e-863c-fb15b74508e6)
Could you please help me get the date in `<core:creationDate>`?

The CityGML file can be downloaded here: https://www.wien.gv.at/ma41datenviewer/downloads/geodaten/lod2_gml/078085_lod2_gml.zip

**Comment by clausnagel** [comment]
The creationDate is set to the import time by default. You can choose a different behaviour in the "Import -> Continuation" preference settings: https://3dcitydb-docs.readthedocs.io/en/latest/impexp/import-preferences/continuation.html

**Comment by Krassnig** [comment]
Thank you very much, that solved the issue.
