### ISSUE TITLE
Import SketchUp models converted to CityGML by FME

### ISSUE THREAD

**Issue by anwar1010** [3dcitydb/importer-exporter#34]
When I Set Geo-location in SketchUp and then I convert SketchUp file using FME desktop. it cannot add a coordinate system in XML or GML file. Because of the coordinate system, I am unable to import or export data using 3DCity DB importer-exporter
[skp2citygml_v1222.2 (backup).zip](https://github.com/3dcitydb/importer-exporter/files/1734518/skp2citygml_v1222.2.backup.zip)
this is the FME for SketchUp to XML converter file for lod3.
@clausnagel

**Comment by anwar1010** [comment]
![capture](https://user-images.githubusercontent.com/11944803/36349831-921fb62c-14ae-11e8-9d8f-0af7fa26a609.PNG)

**Comment by FxKu** [comment]
Sounds like a question for FME users/experts. Would be very strange if setting the CRS in GML is not possible. But yes, you need georeferenced data in order to work with the 3DCityDB.

**Comment by BWibo** [comment]
One other thing that could come in handy if you are trying to convert SketchUp to CityGML is this:
https://extensions.sketchup.com/de/content/cityeditor-2

**Comment by clausnagel** [comment]
Or choose the following which is free: http://www.geores.de/downloads/geores_citygml_tools.zip

**Comment by clausnagel** [comment]
Closing since this is a Sketchup/FME issue rather than an Importer/Exporter issue. Feel free to reopen if have have further questions.
