### ISSUE TITLE
Additional DBOperation Panel to change SRS in database schema

### ISSUE THREAD

**Issue by FxKu** [3dcitydb/importer-exporter#38]
The new release should finally provide a way to let users change the reference system of 3DCityDB instance via the Importer/Exporter GUI. I think, the database operation panel is a suitable place. I would create another tab called `SRS`.

Regarding the code I would reuse the DatabaseSrsComboBox and put two (labesl +) text fields, one checkbox and one button beneath it. Each element in one row. For the text fields I would use the same terminology than in the org.citydb.modules.database.gui.preferences.SrsPanel class (impexp-client module). Not sure, if I should add the check button as well, but probably it makes sense to do so.

I've already added the functions calls to the UtilAdapters. That was pretty easy. But the GUI development might take up more time. Have I missed something?

**Comment by FxKu** [comment]
added a first version in branch srs_operation with commt d40aa38

**Comment by clausnagel** [comment]
based on your work, a SRS operation panel was added to master in f4a43f22727ea5c5549d3575b3865084c4cb92d5.

**Comment by FxKu** [comment]
Looks good to me. :globe_with_meridians:
Thanks. I close it then.
