### ISSUE TITLE
GLTF format is not formed after exporting CityGML file 

### ISSUE THREAD

**Issue by fadelkoto** [3dcitydb/importer-exporter#41]
Hello I am Fadel.
I am currently trying to visualize a dataset of shape file multipatch into Cesium using 3D web client. 
I exported the shp multipatch to CityGML using fme. It was successfull. 
After that I exported the GML into KML/GLTF using BBox option and with the tiling option was clicked. It was succesfull.
However when I try to call the data in the web browser, It only shows a blue line of border (which was Bbox) with no 3d model loaded in the box. I have tried to zoom in but I still found no model.
![image](https://user-images.githubusercontent.com/36468837/39231525-900f0bfc-4894-11e8-9280-e21cbc33ae20.png)
Then I checked the Console in the browser, There are warnings telling that this kind of ID model with .GLTF format is not found.
I checked the root directory and trace the ID. I found that the file with such ID only in .DAE format. 
I tried to search any file with GLTF format in the TILES directory. I found none.
Please help me to resolve this issue.
Thank you.

**Comment by clausnagel** [comment]
Are you sure you checked the option "Create glTF model" on "Preferences -> KML/COLLADA/glTF Export -> General"?

**Comment by fadelkoto** [comment]
Yeah I didnt check it. I just checked it and It is succesfull. Thank You 😃
