### ISSUE TITLE
minor code tweak

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/importer-exporter#45]
Since we've moved the `INDEX_TABLE` to the individual citydb schemas for PostgreSQL (cf. https://github.com/3dcitydb/3dcitydb/commit/5911550054466618ecdb069d46d1395da00e8ce0) , we may need to adjust the following code-line by adding a schema name parameter. 

https://github.com/3dcitydb/importer-exporter/blob/788f142ff80f04bc486b4a963d8a95f01b8919ce/impexp-core/src/main/java/org/citydb/database/adapter/postgis/UtilAdapter.java#L281

**Comment by clausnagel** [comment]
fixed in e3c1ce6152d8594793b0f1616968629ec9003f62
