### ISSUE TITLE
KML citygml is not working in google earth. 3dcitydb citygml 3d importer-exporter Sketchup

### ISSUE THREAD

**Issue by anwar1010** [3dcitydb/importer-exporter#46]
**SketchupDesign**

![5](https://user-images.githubusercontent.com/11944803/41397972-4948b558-6fcf-11e8-84c4-ad7b88c54442.PNG)
[finalkiu2.zip](https://github.com/3dcitydb/importer-exporter/files/2101280/finalkiu2.zip)

**

> I add all my srid and other coordinates in fme..

**
![1](https://user-images.githubusercontent.com/11944803/41397263-1458b53e-6fcd-11e8-8939-f7909552e9bd.PNG)

**Importer exporter import properly**

![2](https://user-images.githubusercontent.com/11944803/41397264-148ad1ae-6fcd-11e8-939b-48e59ddc08ed.PNG)

**My fnal code after export**

![3](https://user-images.githubusercontent.com/11944803/41397265-14bb879a-6fcd-11e8-82ab-767a4d63f125.PNG)
**gml code file**
[finalkiu2.zip](https://github.com/3dcitydb/importer-exporter/files/2101288/finalkiu2.zip)

**This is the issue that not a single building is shown**
![4](https://user-images.githubusercontent.com/11944803/41397268-15342fe2-6fcd-11e8-8fe6-992f2876f7a6.PNG)

**Fme converter I used to conveter my skp file to citygml**

[skp2citygml_v1.2 (backup).zip](https://github.com/3dcitydb/importer-exporter/files/2101205/skp2citygml_v1.2.backup.zip)

@clausnagel @FxKu @yaozhihang @yaozhihang

**Comment by FxKu** [comment]
Sorry to keep you waiting. I took a look at the GML file to understand the issue, but for some reason it only contains bridge windows and doors. In your import report I see only buildings.

Anyway, If the objects are not placed correctly on the globe, usually it's because the wrong coordinate reference is used. If the offset is "small" (say 100km), maybe choose the neighboring UTM zone. If the bounding box looks flipped by 90°, try to swap the X and Y coordinates. If the objects are placed far off,  you probably need another CRS with another datum.

**Comment by anwar1010** [comment]
@FxKu Thank you So much for your support. I will try what you instruct me I think there is a problem with my CRS and datum because the objects are placed far from my original buildings.

**Comment by anwar1010** [comment]
@FxKu When I change the CRS and datum now it's working but I am facing another issue regarding KML
Collada extruded and excel sheet problem
Please have a look at the issue
![issue](https://user-images.githubusercontent.com/11944803/42754815-64ec861e-890f-11e8-8c11-2d616780ed47.PNG)

**Comment by FxKu** [comment]
Hm, are you sure it's the right CRS? You could use a GIS to have a look at the surface_geometry table (geometry column) and compare with an arial image. You can also use the map window of the importer/exporter. It only shows the bounding box of your area, but it's fine for a qick preview.

**Comment by anwar1010** [comment]
Yes, I almost try with every CRS of my country but I still facing such problems sometimes my building is extruded and sometimes it tilts. I usually use importer/exporter bounding box for quick preview they are almost alright.

![issue](https://user-images.githubusercontent.com/11944803/42865505-4a3c1f4e-8a83-11e8-89e8-cb312474eddc.PNG)
![issue2](https://user-images.githubusercontent.com/11944803/42865506-4a758acc-8a83-11e8-881f-506b158d37bc.PNG)

**Comment by FxKu** [comment]
Maybe you can post your question in some Sketchup or FME discussion board. To me it appears that a wrong CRS is the only issue here.

**Comment by FxKu** [comment]
Closing for now as it does not seem to be related with the 3DCityDB tools. Feel free to re-open if I'm wrong ;)
