### ISSUE TITLE
improvement idea for spreadsheet generator

### ISSUE THREAD

**Issue by Crare** [3dcitydb/importer-exporter#50]
Could you add a total number to that generation window and a percentage of completion? This is taking a long time and I would like to see how far it's from completion.

Image below shows what it currently looks like when generating spreadsheet. This is just a minor improvement, but it would be much appreciated.
![spreadsheet_generator](https://user-images.githubusercontent.com/10487241/43068829-2d44b23a-8e74-11e8-82f7-93dc56604aa3.PNG)

**Comment by FxKu** [comment]
What do you think @Son-HNguyen @yaozhihang ? Sounds not too hard to implement.

**Comment by Son-HNguyen** [comment]
Added in https://github.com/3dcitydb/plugin-spreadsheet-generator/commit/c732276bc599b033b592a1b4766e26d6ea078d96. The pop-up window now shows the total number of elements to be exported and the progress bars now also displays the percentage accordingly.
