### ISSUE TITLE
by exporting  KML/COLLADA/glTF Export the glTF files are missing

### ISSUE THREAD

**Issue by AndyLicht** [3dcitydb/importer-exporter#56]
Hi,
i´m using the 4.0.0 version of the the importer/exporter, when i export a little area of my database as KML/COLLADA/glTF the glTF files are missing. I only get the dae files. Have i to convert these files by my self (the examples if the web client are using gltf)?

best regards
Tim

**Comment by Son-HNguyen** [comment]
Closed due to no response. Feel free to reopen if you still have questions.
