### ISSUE TITLE
Error installing in C:(Windows primary drive)

### ISSUE THREAD

**Issue by umarfarooq156** [3dcitydb/importer-exporter#58]
When I installed the 3D city database importer-exporter in primary drive C: on windows 7 ultimate. It doesn't allow me to install it. What should I do? Thank you in advance for the feedback

![error](https://user-images.githubusercontent.com/17993840/47943165-1bd38180-def5-11e8-94c8-13e3373f5b51.png)

**Comment by FxKu** [comment]
Either run the installer as administrator or choose a file directory where your user has write permissions.

**Comment by umarfarooq156** [comment]
Thank you for a quick response. ich hab es dannach versuch auch mit Administrator auf mein notebook. es hat nicht geklappt. aber dannah in D drive es hat funktioniert. thank you  :) I might be using this for my thesis to export the data to PostgreSQL. I am studying at Tu berlin Geodesy and geoinformation.

**Comment by FxKu** [comment]
Ok fine, I'm closing the issue then.

Off topic: I think, I've heard about some work which was dealing with visibility / sun analysis with the 3DCityDB, but I can't point to some existing work, unfortunately. Check the 3DCityDB manual to understand, how the data is organized. If something is unclear to you, use the issue section in the [3dcitydb repo](https://github.com/3dcitydb/3dcitydb/issues).
