### ISSUE TITLE
How to import line-based MultiGeometry

### ISSUE THREAD

**Issue by scar95** [3dcitydb/importer-exporter#59]
My modeling is make with FME to multi-Geometry.
I didn't import my modeling with multi-geometry.
But I read this importer 4.0 version, we can import multi-geometry.
My Import error message this and Failed to resolve XLink reference.

 [23:27:58 ERROR] gen:GenericCityObject 'UUID_fdbc1d8c-dc8e-48fd-aefa-a7bf5543ae61': Unsupported geometry type gml:MULTI_GEOMETRY.
 
If we can't import multi geometry, how did export Mash have Line Model?
Export Collada/Kml to my model has no Line.

Please help me.

**Comment by FxKu** [comment]
Only surface-based MultiGeometry objects are supported. Not MultiPoint or MultiLinestring. Try to change your FME workflow so that it does not write MultiGeometry objects. Should be possible. Other users have managed it as well.

**Comment by scar95** [comment]
Thank you.
Can not export the lines contained in the building?
When importing a building line into a database with multiple curves separately, if i select Export to Kml / Collada, i will need a higher level of Lod. However, my building has a Lod level of 4.

I am sorry if I am strange in English but I am using a translator.

**Comment by clausnagel** [comment]
If you need to import curve geometries for a building, then use the `lodXMultiCurve` property of `Building`,  with 1 < X < 5. 

As @FxKu pointed out, line-based `MultiGeometry` objects are not supported. And I have not seen this being used in any CityGML building model that I have come across so far. Not sure whether I really understand your requirement correctly though.

**Comment by clausnagel** [comment]
Closing this issue since no action is required. Feel free to re-open.
