### ISSUE TITLE
The "Go" on the Map window seems not working...

### ISSUE THREAD

**Issue by umarfarooq156** [3dcitydb/importer-exporter#61]
I tried using Bounding box map window. After writing the desired addressed to be searched,  clicking on the "Go" button and it does not zoom in that desired area. Not sure if it is the Button or some other bug in map windows. It says 

> The maximum query have been reached.

![image](https://user-images.githubusercontent.com/17993840/48510909-7950c200-e855-11e8-93b6-d0ff85eaf398.png)

Any idea why I am getting this error. I wanted to export  the data with the help of bounding box.
with regards

**Comment by umarfarooq156** [comment]
I realized that one could use the bounding box too. But I wanted the specific address or street for example.  For that, I will have to use the search in the address window.

I read about Google API key. I think one has to pay to use Google API if I understood it correctly. 

I had installed the Importer/Exporter through the graphical installer on Windows 7 Ultimate.  Do you mean I will have to uninstall the Importer/Exporter and reinstall it? what about the exported/imported data folder of CityGIML? 

I am going to try it tomorrow as you mentioned.  Thanks for the response. 

Nice weekend 
Regards
Umar

**Comment by clausnagel** [comment]
No, you do not have to uninstall. If you build using `gradlew installDist`, then you will find a full version of the Importer/Exporter in the subfolder `impexp-client/build/install`. You can run the Importer/Exporter from there without affecting your installed version.

If you prefer, you can also build a graphical installer using `gradlew buildInstaller`. After the build, you will find it under `impexp-client/build/distributions`. Simply pick another installation directory during installation to make sure your currently installed version is not affected.

If you want to uninstall the current version though, then note that the uninstaller will delete all files and folder within the installation directory. So if you have created data folders inside the installation directory, then make sure to move them somewhere before to uninstalling.

**Comment by umarfarooq156** [comment]
Alright, It works. I have rebuilt the installer from the master branch using `gradlew buildInstallerand` now I can use the search window. 
Thank you for help

**Comment by umarfarooq156** [comment]
`and`

**Comment by umarfarooq156** [comment]
Alright, It works. I have rebuilt the installer from the master branch using `gradlew buildInstallerand` now I can use the search window. 
Thank you for help
