### ISSUE TITLE
Cannot Install Importer/Exporter on Ubuntu 18.04 Terminal!

### ISSUE THREAD

**Issue by HuyQuoc** [3dcitydb/importer-exporter#64]
Hi, 

I'm trying to install 3DCityDB. I've installed Importer/Exporter-Setup.jar on Ubuntu Terminal but dont have any folder or data as ur documentation. Installed Folder only have two plugins. My Ubuntu doesnt have GUI. Please help me to fix it. 

Thanks & Regards.

**Comment by clausnagel** [comment]
Please review issue #47. I discussed different ways on how to install the Importer/Exporter without a GUI there.

**Comment by clausnagel** [comment]
Closing since discussion was continued in #47.
