### ISSUE TITLE
Exporting as an Excel Spreadsheet gives error

### ISSUE THREAD

**Issue by umarfarooq156** [3dcitydb/importer-exporter#65]
I am not sure if it is only me or it is another bug... Exporting as an Excel spreadsheet would give me an error.  After checking all parameters carefully and even trying all from the front again. the error persisted.
![untitled](https://user-images.githubusercontent.com/17993840/48730025-6b29e980-ec39-11e8-9a30-0a27ec2895aa.png)
![untitled2](https://user-images.githubusercontent.com/17993840/48730026-6b29e980-ec39-11e8-9d42-01f1a82e2d94.png)

Please look at the attachment. 

Regards
Farooq

**Comment by Son-HNguyen** [comment]
Was the Excel file still open while exporting? If that does not solve the problem, can you provide an exerpt of your CityGML file and the template text file used in the screenshot above?

**Comment by umarfarooq156** [comment]
No, the Excel file was not opened while exporting. There was actually no excel file before exporting.  It is supposed to create he exporting excel file, which again it did. But the problem,  When I open this Exported Excel file. it shows the message which I added as an attached picture in my 1st post above there. So when I click on afterwards on this error message, there is nothing inside this exported excel file.
And what CityGML file you are asking for? I made a new file by adding columns and stored it the template and if that's what you are asking about. Please see the attachment of that template file below:

![text_exerpt](https://user-images.githubusercontent.com/17993840/48858331-5f663080-edbb-11e8-8b77-ac95f4bb2355.png)

regards
Farooq

**Comment by Son-HNguyen** [comment]
I see there is a space after `House_Number`. Deleting it should solve the problem.

**Comment by clausnagel** [comment]
We should catch the NPE and provide a more meaningful error message.

@Son-HNguyen, can you have a look at this?

**Comment by Son-HNguyen** [comment]
Done, see commit `Fix NPE when column titles have leading and trailing whitespace` https://github.com/3dcitydb/plugin-spreadsheet-generator/commit/79a62864a9014baf775589688e3f8a252c2129af
