### ISSUE TITLE
Batch file gives error if its path has the character "&"

### ISSUE THREAD

**Issue by Son-HNguyen** [3dcitydb/importer-exporter#67]
Problem: The batch file `3DCityDB-Importer-Exporter.bat` cannot start the Importer/Exporter if its path has a character `&`.
How to reproduce: Simply rename the Importer/Exporter home folder to something like `Importer & Exporter v4.0.0` and then launch the batch file `3DCityDB-Importer-Exporter.bat` from `bin`.

**Comment by clausnagel** [comment]
The starter scripts are auto-generated by the Gradle Application plugin. So I think this issue should be reported in the [Gradle forums](https://discuss.gradle.org/). 

For the meantime, my obvious recommendation would be that you try and avoid placing the Importer/Exporter into a path that contains special characters.
