### ISSUE TITLE
Cannot run CREATE_DB.SH on Ubuntu 16.04!

### ISSUE THREAD

**Issue by HuyQuoc** [3dcitydb/importer-exporter#69]
Hi, 

I create new tickit here. I've installed Importer/Exporter on Ubuntu 16.04. I also installed PostgreSQL 9.6, PostGIS 2.3 and others components. But when I run CREATE_DB.SH, I got an error: 

> Please enter a valid SRID (e.g., EPSG code of the CRS to be used).
> (SRID must be an integer greater than zero): 3068
> CREATE_DB.sh: 51: CREATE_DB.sh: [[: not found
> 
> Please enter the EPSG code of the height system (use 0 if unknown or '3068' is already 3D).
> (default HEIGHT_EPSG=0): 5783
> CREATE_DB.sh: 66: CREATE_DB.sh: [[: not found
> 
> Please enter the corresponding gml:srsName to be used in GML exports.
> (default GMLSRSNAME=urn:ogc:def:crs,crs:EPSG::3068,crs:EPSG::5783):
> 
> Connecting to "@:/" ...
> Default footer is off.
> SET
> psql:CREATE_DB.sql:36: ERROR: function postgis_version() does not exist
> LINE 1: SELECT postgis_version();
> ^
> HINT: No function matches the given name and argument types. You might need to add explicit type casts.
> 
> CREATE_DB.sh: 92: read: Illegal option -s 

I created super user postgres, create new citydb databasae, owner to database, create postgis extension, create postgis_sfcgal extension, edit CONNECTION_DETAILS.SH. I also success in command select postgis_version(); with super user postgres. So I know why CREATE_DB.SH cannot be done. 

Please help me to fix it. 
Thanks.

**Comment by clausnagel** [comment]
Your shell does not seem to support `[[`, which is used in the scripts. `[[` is a bash-builtin. So how are you running the script? Make sure you run it with a _bash_ shell and not with _sh_. If you used:

`$ sh CREATE_DB.sh`

then try:

`$ bash CREATE_DB.sh` 

It should also work to make the script executable and run it via:

`$ ./CREATE_DB.sh` 

In this case, the shebang in the script should cause `/bin/bash` to be used.

**Comment by HuyQuoc** [comment]
> Your shell does not seem to support `[[`, which is used in the scripts. `[[` is a bash-builtin. So how are you running the script? Make sure you run it with a _bash_ shell and not with _sh_. If you used:
> 
> `$ sh CREATE_DB.sh`
> 
> then try:
> 
> `$ bash CREATE_DB.sh`
> 
> It should also work to make the script executable and run it via:
> 
> `$ ./CREATE_DB.sh`
> 
> In this case, the shebang in the script should cause `/bin/bash` to be used.

Hi, 
I did as u said. But it return same error. I still not fix it. 
Thank you,
Regards.

**Comment by clausnagel** [comment]
Did a fresh install of Ubuntu 16.04 and was able to run `CREATE_DB.sh` without errors. So, I still assume that you do not use a _bash_ shell for running the script.

What is the output of the following commands on your machine:

`$ /bin/bash --version`

`$ /bin/bash -c "type [["`

**Comment by HuyQuoc** [comment]
> /bin/bash -c "type [["

Hi Clausnagel, 

I tried 2 fresh Ubuntu 16.04 but have same error. Here is output of my commands: 

postgres@b5c6a2ed0db1:/DockerShared/3dcitydb/3dcitydb/postgresql/ShellScripts/Unix$ /bin/bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

> postgres@b5c6a2ed0db1:/DockerShared/3dcitydb/3dcitydb/postgresql/ShellScripts/Unix$ /bin/bash --version
> GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
> Copyright (C) 2013 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> 
> This is free software; you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> postgres@b5c6a2ed0db1:/DockerShared/3dcitydb/3dcitydb/postgresql/ShellScripts/Unix$ /bin/bash -c "type [["
> [[ is a shell keyword

Thanks & Regards.

**Comment by clausnagel** [comment]
Thanks, the outputs look fine. Sorry, I am not sure why the scripts are failing on your machine, and it's hard to debug since there are no errors on my Ubuntu box.

The `CREATE_DB.sh` is simply a convenience wrapper for the SQL script `3dcitydb/postgresql/SQLScripts/CREATE_DB.sql` script (see line 89 of the script). The `CREATE_DB.sh` script is only used to query required parameters from the user. The creation of the 3DCityDB instance is then performed by `CREATE_DB.sql`.

So, as an alterantve, you could try to directly run `CREATE_DB.sql` by passing all required parameters manually:

`$ psql -d your_database -h your_host -p your_port -U your_username -f CREATE_DB.sql -v srsno=your_srs -v gmlsrsname=your_gml_srsname`

Note that the `-f` parameter must provide the full path to the `CREATE_DB.sql` script. The values for the parameters `srsno` and `gmlsrsname` are those queried by the `CREATE_DB.sh`. The values for the parameters `-d`, `-h`, `-p` and `-U` can be copied from your `CONNECTION_DETAILS.sh` script.

An example call for setting up a 3DCityDB with EPSG:25832 would look like this:

`$ psql -d citydb -h localhost -p 5432 -U postgres -f CREATE_DB.sql -v srsno=25832 -v gmlsrsname=urn:ogc:def:crs:EPSG:25832`

**Comment by HuyQuoc** [comment]
> Thanks, the outputs look fine. Sorry, I am not sure why the scripts are failing on your machine, and it's hard to debug since there are no errors on my Ubuntu box.
> 
> The `CREATE_DB.sh` is simply a convenience wrapper for the SQL script `3dcitydb/postgresql/SQLScripts/CREATE_DB.sql` (see line 89). The `CREATE_DB.sh` script is only used to query required parameters from the user. The creation of the 3DCityDB instance is then performed by `CREATE_DB.sql`.
> 
> So, as an alternative, you could try to directly run `CREATE_DB.sql` by passing all required parameters manually:
> 
> `$ psql -d your_database -h your_host -p your_port -U your_username -f CREATE_DB.sql -v srsno=your_srs -v gmlsrsname=your_gml_srsname`
> 
> Note that the `-f` parameter must provide the full path to the `CREATE_DB.sql` script. The values for the parameters `srsno` and `gmlsrsname` are those queried by the `CREATE_DB.sh`. The values for the parameters `-d`, `-h`, `-p` and `-U` can be copied from your `CONNECTION_DETAILS.sh` script.
> 
> An example call for setting up a 3DCityDB with EPSG:25832 would look like this:
> 
> `$ psql -d citydb -h localhost -p 5432 -U postgres -f CREATE_DB.sql -v srsno=25832 -v gmlsrsname=urn:ogc:def:crs:EPSG:25832`

Hi clausnagel, 

Thank you so much, I installed 3DCityDB and now I'm trying to import GML data to 3DCityDB. Do u have any comment for importing GML data with textures, patterns, etc ? And If my GML used in another CRS, can i transform CRS to create 3DTiles for CesiumJS ?

Regards.

**Comment by FxKu** [comment]
Please, take a look at the manual page 216 and following. It explains, how to use the impexp-client-4.0.0.jar. It has an -import operation which has to followed by a file name. You can also specify a config.xml file but the default settings should also work in your case. If you need to change the CRS, you can use the `change_schme_srid` function in the database. This is also explained in the manual.

**Comment by HuyQuoc** [comment]
> Please, take a look at the manual page 216 and following. It explains, how to use the impexp-client-4.0.0.jar. It has an -import operation which has to be followed by a file name. You can also specify a config.xml file but the default settings should also work in your case. If you need to change the CRS, you can use the `change_schme_srid` function in the database. This is also explained in the manual.

Thanks for your quick reply, FxKu. I found import guide using CLI in page 216. But I cannot find template of config.xml on my machine. Can u share config folder on Ubuntu 16.04 to me ?

I used impexp-config to automatically create config file and got this message: 

> root@b5c6a2ed0db1:/DockerShared/3dcitydb/lib# java -jar impexp-config-4.0.0.jar
> no main manifest attribute, in impexp-config-4.0.0.jar

Regards.

**Comment by FxKu** [comment]
Hm, to be honest I'm surprised to find things like `swing` and `awt` classes in the stack trace. Maybe the `impexp-client-4.0.0.jar` is not the correct JAR. Maybe it's the one with `core` in the name? Maybe @clausnagel knows more. Last time I've used the CLI interface is ages ago....

**Comment by clausnagel** [comment]
1. If you want to start the non-GUI version of the Importer/Exporter, then you have to use the `-shell` parameter (see p. 217 of the manual)
2. The `impexp-config.jar` is not executable. You may use it in your own Java code to create a configuration programmatically.

@HuyQuoc my strong recommendation is that you use the GUI version of the Importer/Exporter on some other machine first. Then you can try different settings and understand how they are represented in the `project.xml`. Once you have a configuration that suits your needs, you can use it for the non-GUI version.

**Comment by HuyQuoc** [comment]
> 1. If you want to start the non-GUI version of the Importer/Exporter, then you have to use the `-shell` parameter (see p. 217 of the manual)
> 2. The `impexp-config.jar` is not executable. You may use it in your own Java code to create a configuration programmatically.
> 
> @HuyQuoc my strong recommendation is that you use the GUI version of the Importer/Exporter on some other machine first. Then you can try different settings and understand how they are represented in the `project.xml`. Once you have a configuration that suits your needs, you can use it for the non-GUI version.

Nice. Thank you @clausnagel . Do u have plan for next release ?

**Comment by FxKu** [comment]
What's the next release got to do with it? You can use the GUI version already to generate the project.xml file. Were you able to get it working?

**Comment by HuyQuoc** [comment]
Hallo. I'm complete to install and import CityGML but I have new problem with export to KML/GLTF to display with 3DWebMapClient. So I'll create new issue. Please close this issue. 

Thanks, 
Regards.

**Comment by FxKu** [comment]
Alright :)
