### ISSUE TITLE
Exported glTF files don't include embedded textures

### ISSUE THREAD

**Issue by donatomarro** [3dcitydb/importer-exporter#7]
Hello,

I'm using the Cesium branch of the importer-exporter and I'm trying to export a textured building into one single glTF file (with embedded textures). Next to the created .dae and .jpeg files there is a glTF file, but it doesn't include the textures (just links to the texture files):

```
    "images": {
        "textureAtlas_1360110664_0_img": {
            "name": "textureAtlas_1360110664_0_img",
            "uri": "textureAtlas_1360110664_0.jpeg"
        },
        "textureAtlas_1360110664_1_img": {
            "name": "textureAtlas_1360110664_1_img",
            "uri": "textureAtlas_1360110664_1.jpeg"
        }
    },
```

When I'm running an export without glTF (creating solely the .dae and .jpeg files) and then perform a manual conversion using the collada2gltf tool (with option -e), it results in a glTF file that also includes the textures:

```
    "images": {
        "textureAtlas_1172405395_0_img": {
            "name": "textureAtlas_1172405395_0_img",
            "uri": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJ...
        },
        "textureAtlas_1172405395_1_img": {
            "name": "textureAtlas_1172405395_1_img",
            "uri": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJ...
        }
    },
```
I had a look a the KmlExporterManager and saw that the call to the collada2gltf tool happens before the images are saved to disk. So I changed the order (first saving the images, then calling collada2gltf), but the result is still the same. Any idea why the textures don't get embedded into the glTF file during the export but they do when I'm executing the collada2gltf tool inside my windows CLI?

Best regards,
Donato

**Comment by donatomarro** [comment]
So I was able to fix this problem now. :-)

In addition to move the 'generate gltf model from collada' block behind the 'image saving' block (otherwise the collada2gltf tool will start converting before all textures are written to disk) you also have to change the following lines 

```
ProcessBuilder pb = new ProcessBuilder(collada2gltfPath, "-f", buildingDirectory + File.separator + colladaBundle.getGmlId() + ".dae",  "-e", "true"); 
pb.start();
```
into
```
ProcessBuilder pb = new ProcessBuilder(collada2gltfPath, "-f", colladaBundle.getGmlId() + ".dae",  "-e", "true");
pb.directory(buildingDirectory);
pb.start();
```
to set the right working directory for collada2gltf to make it find the texture files.

**Comment by yaozhihang** [comment]
Hi Donato,

thank you for your input.

There are two reasons why I don't want the textures to be embedded in the glTF file. 
1. The entire files size can be reduced since the exported .dae and .gltf  assets share the common textures
2. Cesium (starting from version 1.16 ) supports incremental loading of glTF model’s textures. This feature may give a better user experience when loading glTF models with detached textures.

best regards,

Zhihang

**Comment by donatomarro** [comment]
Hi Zhihang,

> The entire files size can be reduced since the exported .dae and .gltf assets share the common textures

But in which case would you need both, the .dae and the .gltf files? I made some changes to the exporter so that the .dae and .jpeg files will be deleted after creating the .gltf and the .kml files will reference the .gltf file instead of the .dae. So there isn't an increase in files size.

> Cesium (starting from version 1.16 ) supports incremental loading of glTF model’s textures. This feature may give a better user experience when loading glTF models with detached textures.

Yes, I noticed that. So I will go back to detached textures I guess. 

Best regards,
Donato

**Comment by yaozhihang** [comment]
Hi Donato,

combined with COLLADA .dae files the exported 3D models can be visualized not only in Cesium but also in Google Earth by using the KML file which is located in the same folder as the master JSON file. It could be useful in many use cases.

best regards,

Zhihang

**Comment by donatomarro** [comment]
Hi Zhihang,

I see. I'm still wondering how the exported gltf files are loaded into Cesium. Maybe you can give me  a little hint about this?

In my application I'm adding a new collada layer like this:

```
colladaLayer = new CitydbKmlLayer({
    url : './data/berlin_collada_MasterJSON.json'
});
```
It works fine. And it still works when I'm deleting the .dae files so that there are only the .gltf and .jpeg files left in the tiles directories. I wasn't able to find out how the .gltf files are referenced, since the files like berlin_Tile_0_1_collada.kml only contain links to the .dae files.

Best regards,
Donato

**Comment by yaozhihang** [comment]
Hi Donato,

the referencing of .dae files is internally switched to the glTF files by the 3dcitydb-web-map
https://github.com/3dcitydb/3dcitydb-web-map/blob/master/js/CitydbKmlDataSource.js#L1341

best regards,

Zhihang

**Comment by donatomarro** [comment]
Hi Zhihang,

found the code line one minute ago. ;-) But thanks!

Best regards
Donato
