### ISSUE TITLE
SQL error while querying the highest available LOD: column pc.lod4multi_solid_id does not exist

### ISSUE THREAD

**Issue by DKKepinski** [3dcitydb/importer-exporter#72]
Hello,

We are using the importer exporter to load citygml files into 3dcitydb web map.
We have multiple feature types. We have started with buildings and that went well – we were able to import the citygml into 3dcitydb, then export the kml, and load this kml into the 3dcitydb web map. So far so good.

Then we have tried the same with a different feature type, this one of the veg:PlantCover type. Unfortunately it went wrong on the second step: exporting the kml. 

We are getting this error:

 ![error](https://user-images.githubusercontent.com/11194319/50004097-4dd10c80-ffa6-11e8-8a13-41c6dc60e3b6.png)

This seemed odd to us, so we checked our data against the citygml spec – and it checks out, nothing weird to see here. Then we decided to check the code of the importer exporter and came across this snippet:
 
![codesnippet](https://user-images.githubusercontent.com/11194319/50004109-54f81a80-ffa6-11e8-8c24-1f32ba52c725.png)

The geo-domain and the software is pretty new to us, but this code snippet seemed odd to us. If nothing else, it is inconsistent: _multi_surface_id vs multi_solid_id. Notice the missing underscore in the second example, and the error message: pc.lod4multi_solid_id does not exist Hint: Perhaps you meant to reference the column “pc.lod4_multi_solid_id”.

It seems to us that our issue could be caused by this mismatch. Could this be correct? And if so, are there any workarounds / solutions for this problem?

Thank you in advance,

Dominik Kepinski

**Comment by clausnagel** [comment]
Thanks for reporting this bug. Yes, as you assume an underscore is missing in the Java code.

**Comment by clausnagel** [comment]
Fixed in 843fcc6d5009fe6e4b9d2a3cd128ef28c404752c. You can checkout the master branch and build the Importer/Exporter from source (see [here](https://github.com/3dcitydb/importer-exporter#building)). Please report here if the fix does not solve the problem.

**Comment by DKKepinski** [comment]
Thank you for quick response!

After building from master i am getting this error:

![newerror](https://user-images.githubusercontent.com/11194319/50006039-b4592900-ffac-11e8-8af1-418162ae4e89.png)

This probably has something to do with a discrepancy between master branch and the release, so i will have to find out why this is happening first.

I'll keep you posted when i know more.

**Comment by DKKepinski** [comment]
It works!

You have made us very happy!

Thank you very much :)
