### ISSUE TITLE
Correct path for tiled export?

### ISSUE THREAD

**Issue by yuqli** [3dcitydb/importer-exporter#73]
Thanks for making the tool! I had been using 3D City Database for 8 days until finally found this Github project... So happy to finally find a community after some trials and errors! 

My question is how to correctly set up the export path when I want to do tiled export. I have 1) activated spatial indices under the "database" tab and 2) specified number of bounding boxes in the "preference" -> "Bounding Box" tab and 3) specified the bounding area in the "Export" tab. It seemed these would be enough for the program to start tiled export.

But a remaining issue is how to set up the export path in the "Export" tab. From page 142 of the documentation, it is stated that : 

> The export operation supports tiled exports, which typically results in multiple datasets being written to the file system. Nevertheless, also for tiled exports, only a single target file must be specified. More details on tiled exports are provided in chapter 5.6.2.2.

... which is kind of confusing. For tiled export, there should be multiple documents / folders, I'm wondering how to properly set up a "single target file"? I tried setting up a folder, but this is not allowed. 

If I specify a single file name, say "test.gml", it seemed the program will output multiple folders (named "tile_0_1") that all contain a single "test.gml". However in my last attempt these "test.gml" files are all 0 bytes. More, outside these "tile_x_y" folders, there is also a "test.gml" file. 

My last program crashed though, likely be a memory error. I am currently attempting to try this again. But just curious is this supposed to be like this or am I missing something to properly export a .gml file in tiles?

Thanks a lot!

**Comment by clausnagel** [comment]
Well, we wanted to avoid multiple output file dialogs for tiled and non-tiled exports. But I see that it might be confusing.

First, your settings are correct. For a tiled export, you need to 1) activate the spatial indexes, 2) define a bounding box, and 3) activate tiling in the preferences. Then you define the "target file" like, for instance, `/home/my_3d_city_model/test.gml`.

The exporter takes the path `/home/my_3d_city_model/` as base path. For every tile to be exported, a separate subfolder will be created. Per default, the subfolders will be named `tile_x_y`, with x and y being the row and column of the current tile. Each tile is then stored within its subfolder as file `test.gml` as specified in the above "target file". 

The preferences dialog lets you change the names for the subfolders and optionally choose a tile-specific suffix for the filenames. Hope this makes it clear. 

Regarding your further questions/issues:

1. For a tiled export, no file is written outside `/home/my_3d_city_model/tile_x_y/` in the above example. If you find a file say at `/home/my_3d_city_model/`, then this must be from a previous export.
2. If there are not city objects on one of the tiles, the exporter will write an empty `<CityModel>` into the target CityGML file. So the file size should never be 0 bytes.
