### ISSUE TITLE
 Best way to output buildings in a large .gml file into individual .obj / .ply files?

### ISSUE THREAD

**Issue by yuqli** [3dcitydb/importer-exporter#74]
So I had a very large .gml file (30GB) which is the LoD2 map of New York City. 

I am trying to output all individual buildings into either .obj or .ply files. e.g. suppose I have in total 100,000 buildings in the GML file, I would like to output 100,000 .obj or .ply files, each named by a unique identifier like building ID.

It seems this goal need to tackle two broad technical challenges:

- Extract all buildings in the .gml file into individual files (either .gml or .obj)
- Convert .gml files into .obj files

These two challenges are complicated by the fact that there are so many buildings and the file is too large to process. Specifically, there are the following issues:

- The original .gml file is too large to be load directly into converters like FME data inspector 
- With the help of the 3D Database, I can output the original file into tiles and theoretically load every tile into FME data inspector, before converting individuals buildings into its own point cloud / mesh. However, this is not optimal because suppose I have 100 tiles I need to manually do this 100 times, which does not sound very pleasant.
- I know another tool named CityGML2OBJs (https://github.com/tudelft3d/CityGML2OBJs) which is a Python script and can be run programmatically. However, this tool does not seem to be very stable - I have not able to successfully run it through till now. More, I am not sure it can extracting individual buildings. If not, then I am back with the "too many tiles to handle manually" problem.

I would like to ask if there is a recommended way to programmatically do this. Any advice would be helpful. Thanks a lot!

**Comment by clausnagel** [comment]
I would start with a tiled export, and then create an FME workspace that iterates over all CityGML files and creates one OBJ file for every building. Should not be too tough and should not require any manual interaction. 

But I am not an FME expert. I saw that you already started a [thread](https://knowledge.safe.com/questions/84869/output-buildings-into-individual-obj-files.html) in the FME forum, and I think this is the right place to get more help.
