### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by DanMurtin** [3dcitydb/importer-exporter#75]
Hello,
I am trying to import my gml file into my database, and I get the following error:
                       The feature type filter must not be empty.
What is the problem? It sounds like I did not check any of the options from the Feature Type list, but I have types selected. I have exported the GML using FME, where I have selected  LoD name: lod2MultiSurface and feature Role: consistsOfBuildingPart. Not sure if that could be the issue.

the GML file (no textures folder): 
[GML.txt](https://github.com/3dcitydb/importer-exporter/files/2773249/GML.txt)

**Comment by DanMurtin** [comment]
I resolved it by downgrading from 4.0.1 to 4.0.0

**Comment by clausnagel** [comment]
Thanks for reporting this bug. Fixed in 08a0b263b54a87aba5001417193adb2ccac2b5cd
