### ISSUE TITLE
NPE Error while importing CityGML file with Affine Transformation

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/importer-exporter#77]
The CityGML Importer/Exporter throws a NPE error during CityGML Import if the affine transformation with `Swap X/Y` is applied. 
Detiled error message:  
![image](https://user-images.githubusercontent.com/5942971/52480699-bdc9d080-2bac-11e9-95e5-43ae10cc84b3.png)

**Comment by clausnagel** [comment]
Fixed in 58102f58c409455346819425e8f481c891b2514b
