### ISSUE TITLE
Could not display object

### ISSUE THREAD

**Issue by jkumar80** [3dcitydb/importer-exporter#79]
Hi,

I tried to export the data to KML/COLLADA format in order to view the data in web using cesium. At the time conversion I encountered an error "Could not display object <GMLID> as extruded from any LOD.

Kindly help me to resolve this issue.

Thanks.

Best Regards,
K.Jayakumar

**Comment by Son-HNguyen** [comment]
Could you provide a screenshot of your export and preferences tab as well as a small excerpt of your data so we can test?

**Comment by Son-HNguyen** [comment]
Closed due to inactivity. Please feel free to reopen if you still have any issues.
