### ISSUE TITLE
KML/COLLADA/glTF Export - Unexpected Result

### ISSUE THREAD

**Issue by FLeinen** [3dcitydb/importer-exporter#80]
Hi everyone,

I am working on the [Hands-On-Tutorial for beginners](https://github.com/3dcitydb/tutorials) using the given Berlin dataset and I am stuck on exercise 6.1 (KML/COLLADA/glTF Export).
When I click _export_ in the _KML/COLLADA/glTF Export_-tab no error occurs and all files are generated:
![00_generatedfiles](https://user-images.githubusercontent.com/30873875/53347609-c0048c80-3919-11e9-9371-c434f69c5560.png)
Anyway, the kml-file does not look like I've expected. This is how Google Earth Pro visualizes the kml-file (find all generated files below):
![00_gep](https://user-images.githubusercontent.com/30873875/53391924-31832000-3998-11e9-858c-0bdaaaf0783a.png)
There are also no 3D buildings visible in Berlin.
What am I doing wrong?

I am using Ubuntu 18.04 with impexp-client version 4.2.0 (had the same issue with 4.0 before) and Java SE Runtime Environment (build 1.8.0_201-b09).

My exported Files:
[Layer 1.zip](https://github.com/3dcitydb/importer-exporter/files/2904067/Layer.1.zip)

My settings:
![00_kml](https://user-images.githubusercontent.com/30873875/53392781-bcfdb080-399a-11e9-9848-0ef4cc472333.png)
![00_preferences](https://user-images.githubusercontent.com/30873875/53392783-be2edd80-399a-11e9-946e-c23c31c39c13.png)

Console:
[16:08:35 INFO] Initializing database export...
[16:08:35 INFO] Checking for spatial indexes on geometry columns of involved tables...
[16:08:35 INFO] 121 (11x11x1) tiles will be generated.
[16:08:35 INFO] Exporting to file: /home/fabian/Documents/RTG_Schulungskurs_2016/Exports/KML/Layer 1/Tiles/0/0/Berlin_Buildings_Layer1_Tile_0_0_extruded.kmz
[16:08:35 INFO] Exporting to file: /home/fabian/Documents/RTG_Schulungskurs_2016/Exports/KML/Layer 1/Tiles/0/1/Berlin_Buildings_Layer1_Tile_0_1_extruded.kmz

...

[16:08:39 INFO] Exporting to file: /home/fabian/Documents/RTG_Schulungskurs_2016/Exports/KML/Layer 1/Tiles/10/10/Berlin_Buildings_Layer1_Tile_10_10_extruded.kmz
[16:08:39 INFO] Exported city objects:
[16:08:39 INFO] bldg:Building: 954
[16:08:39 INFO] Processed geometry objects: 1727
[16:08:39 INFO] Total export time: 04 s.
[16:08:39 INFO] Database export successfully finished.

Best
Fabian

**Comment by FxKu** [comment]
Looks like you're using the wrong reference system.

**Comment by FLeinen** [comment]
Thank you for your prompt response.
I have just copied the SRID from the [docker manual](https://hub.docker.com/r/tumgis/3dcitydb-postgis#linux-bash). With the right SRID it works fine.
As someone who never got in touch with GIS before, I did not even realize that there is a choice regarding the coordinate system.

**Comment by syahiirahS** [comment]
Hi usrFabian,

I'm trying to learn 3DCityDB using the tutorial. But, I don't have the dataset used in the tutorial and the link is no longer working. I hope you can share the dataset with me.

Best,
Syahiirah

**Comment by Son-HNguyen** [comment]
Hi Syahiirah,

I've just fixed the [tutorial data link](https://www.3dcitydb.de/3dcitydb/fileadmin/TUM_Workshop/RTG_Schulungskurs_2016.zip). It should work now.

Best,
Son

**Comment by syahiirahS** [comment]
> Hi Syahiirah,
> 
> I've just fixed the [tutorial data link](https://www.3dcitydb.de/3dcitydb/fileadmin/TUM_Workshop/RTG_Schulungskurs_2016.zip). It should work now.
> 
> Best,
> Son

Hi Son,

Many thanks.

Best, 
Syahiirah

**Comment by Son-HNguyen** [comment]
You're welcome. ;-)
