### ISSUE TITLE
Visulaize only one object 

### ISSUE THREAD

**Issue by ayman-aljullaq** [3dcitydb/importer-exporter#84]
Hello,

I have a KML/COLLADA/glTF folder for a city and this file was extracted from the importer/exporter tool and I just want to visualize one object, e.g. building. Can you please tell me, what's the best solution for that and should I always use the importer/exporter tool to extract the data I want to visualize?

Thank you

**Comment by Son-HNguyen** [comment]
Hi,

sounds a lot similar to this https://github.com/3dcitydb/3dcitydb-web-map/issues/18#issuecomment-309669613.

**Comment by Son-HNguyen** [comment]
Closed due to inactivity. Please feel free to reopen if you still have any issues.
