### ISSUE TITLE
gltf Export

### ISSUE THREAD

**Issue by synpc** [3dcitydb/importer-exporter#87]
hi gurus
my collada export with texture (embedded gltf) loads vvvery sloooowly in web client;
have tried to reduce size of jpg files, only slight improvement;
any tips to optimise / speed up process 
will be greatly appreciated
thnx

**Comment by Son-HNguyen** [comment]
The loading speed depends on many factors, such as computer configurations, CPU and GPU capability, etc. Regarding the 3DCityDB KML/COLLADA/glTF Export, you could either change the scaling of textures to some smaller values in the rendering preferences or try with and without embedding textures in the glTF files and test which is faster in your use case. See starting from page 199 of the [Documentation](https://github.com/3dcitydb/importer-exporter/blob/master/resources/manual/3DCityDB_Documentation_v4.0.pdf).

**Comment by synpc** [comment]
thanks for tips;
have tried various combinations of scaling: loading of export with scaling 0.2, down from initial 0.5, perceptible improvement; will report further after trying embed vs non-embed;

**Comment by Son-HNguyen** [comment]
Closed due to inactivity. Please feel free to reopen if you still have any issues.
