### ISSUE TITLE
Single model output for glTF export

### ISSUE THREAD

**Issue by ghost** [3dcitydb/importer-exporter#90]
Hi,

I was just wondering if there is a dedicated way to export to a single model/file?
No matter how high I set the value "put objects together in groups of" in rendering->building preferences, I always end up with a large number of files...

Regards,
Ludwig

**Comment by Son-HNguyen** [comment]
Sounds similar to #84 and https://github.com/3dcitydb/3dcitydb-web-map/issues/18#issuecomment-309669613. Alternatively, you could try deactivating tiling during export to reduce the number of folders and files.

**Comment by Son-HNguyen** [comment]
Closed. Feel free to reopen if you still have any issues.
