### ISSUE TITLE
Bug while exporting PlantCover with importer/exporter 4.x

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/importer-exporter#91]
Hi,

while using the importer/exporter 4.2.1 (with 3DCiyDB 4), I can correctly validate and successfully import a file containing PlantCover objects. 
However, whenever I try to export it, the process fails throwing these errors:

[10:57:15 INFO] Found 50 top-level feature(s) matching the request.
[10:57:15 ERROR] An error occurred: null
[10:57:15 ERROR] Aborting due to an unexpected java.lang.NullPointerException error.
[10:57:15 INFO] Cleaning temporary cache.
[10:57:15 WARN] Database export aborted.

Please note that using the importer/exporter 3.3.2 (with 3DCityDB 3), everything works.

I attach here a sample of the dataset which is causing issues.

I am using PostgreSQL 9.6 with PostGIS 2.5.

[test_veg_plantcover.zip](https://github.com/3dcitydb/importer-exporter/files/3280528/test_veg_plantcover.zip)

**Comment by clausnagel** [comment]
Thanks Giorgio for reporting this bug. I just fixed it in 97043081aebd20d6d1a619ece03d427174925886.

If you need the bugfix before the next release of the Importer/Exporter, then you can easily build your own intermediate version from the `master` branch following these steps: https://github.com/3dcitydb/importer-exporter#building
