### ISSUE TITLE
No KML export of BuildingInstallations modelled as ImplicitGeometry?

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/importer-exporter#93]
Dear developers,

A question to you, as I could not find it in the documentation (or I may have missed it) of the 3DCityDB (3.x).

I have a number of LoD2 buildings. Additionally, they have some (outer) BuildingInstallations which are modelled geometrically via lod2ImplicitRepresentation (using MultiSurfaces).

I can validate the CityGML input file in the 3DCityDB importer, I can import it correctly into the 3DCityDB, but I cannot export the BuildingInstallations using the 3DCityDB KML exporter.

Is is a bug or it is just not supported?

If I model each BuildingInstallation "as usual" via lod2Geometry (again, using MultiSurfaces), than it the exporter works as expected.

If needed, I can provide an exerpt of the CityGML file. Let me know!

**Comment by clausnagel** [comment]
Hi @gioagu, well, it should work but it seems like we never tested this scenario. Would be great if you can provide us some test data so that we can fix this issue. Does the CityGML export work correctly?

**Comment by gioagu** [comment]
Here you go.
This is exported from the 3DCityDB. I'd say, yes, the exporter works.
There are for each building 3 BuildingInstallations. They look like spheres on top of the buildings.
The lowest one is modelled as lod2Geometry, the other 2 as lod2ImplicitGeometries (Solid and MultiSurface, respectively).
In FZK you can visualise them easily.

The KMZ exporter only exports the first one.

The zipped CityGML file is attached: [Test_mini_out.zip](https://github.com/3dcitydb/importer-exporter/files/3306770/Test_mini_out.zip)

**Comment by clausnagel** [comment]
Thanks @gioagu. I checked the current implementation. Implicit geometries are only considered by the KML/COLLADA/glTF exporter if they are modelled for top-level features (such as `frn:CityFurniture` or `gen:GenericCityObject`) but not for nested sub-features such as `bldg:BuildingInstallation`. 

So, the KML/COLLADA/glTF exporter needs to be enhanced to support your test dataset correctly. I am going to work on it, but it may take a bit more time. I will post updates here.

**Comment by clausnagel** [comment]
Fixed in `master` branch (1177b6657fc963cbb51c3fd1f5aadb32f5189757). Below the exported model is shown in Google Earth.

![ge](https://user-images.githubusercontent.com/5517439/60253683-da9d4100-98cc-11e9-855a-54a62821631f.png)

**Comment by clausnagel** [comment]
Closing. Feel free to reopen if the issue still occurs.
